"""Assemble jp/jesr_detail.json -- per-company ESR detail pages for jp/company.html.

Publishing-stage builder (stdlib only). Contract is fixed with designer -- do not
rename keys. See inbox/publishing/20260912T1120Z__owner__JP_MULTI__jesr_detail_json.md
for the full contract and inputs.

Inputs:
  J-ESR/raw/fy2025_samples/extracted_sample_values.json  (per-item extraction + checks;
      generated by J-ESR/extract_esr_template_samples.py -- run automatically if missing)
  J-ESR/esr_disclosure_schema.json                        (item id -> labels/unit/kics_item_ref)
  J-ESR/esr_aggregation_rules.json                        (rules_ref pointer only; the
      known_deviations it documents are already reflected in the per-check "note" fields
      inside extracted_sample_values.json, so nothing further is merged from it here)
  jp/jesr_esr.json                                        (published headline + source
      metadata for company records; used for the self-check cross-reference)
  J-ESR/jesr_master.json                                  (pre-exclusion master -- the
      published jp/jesr_esr.json intentionally drops source_url/doc_type/doc_date/
      preliminary for excluded subsidiaries such as meijiyasuda_nonlife, so those four
      fields are looked up here instead of being left blank)

Companies included: census.status == "posted" (au_nonlife, meijiyasuda_nonlife -- full ESR
layer) PLUS, since 2026-09-13 (inbox/jp/20260913T0330Z), census.status == "not_yet" companies
that have the profit AND history layers extracted (tokiomarine_nichido, mitsui_sumitomo,
sompo_japan -- ESR due 2026-10-31). A not_yet company carries esr_status "not_yet", an
esr_placeholder {phrases, pages, expected}, headline with null ESR values, empty capital/
items/sensitivity/capital_tree/risk_tree, all-null risk/market_sub, and the same profit/
history/profit_flow blocks as a posted company. nnlife (not_yet, no history layer) stays out.
_meta.coverage: detail_total / esr_posted / esr_not_yet (replaces the old detail_posted).

Each included company also gets a "profit" block (layer:"profit" in the schema, added
2026-09-12 per inbox/publishing/20260912T1240Z__owner__JP_MULTI__jesr_detail_profit_block.md).
"items" holds every non-null profit:pl/uw/inv id for that company; "ratios" (nonlife
loss/expense/combined ratio) and "core" (life 基礎利益 decomposition + 三利源) are
convenience sub-views that duplicate a subset of the same ids -- same "items" + narrower
view pattern already used above for capital/risk/market_sub. meijiyasuda_nonlife has no
profit tables in its excerpt volume (main volume blocked, see extract_esr_template_samples.py)
so its profit.status is "not_obtained" and items/ratios/core are all empty.

Each included company also gets a "history" block (layer:"history" in the schema, added
2026-09-12 per inbox/jp/20260912T1440Z__owner__JP_MULTI__pl_history_5y.md) -- 5 fiscal years
(FY2021..FY2025) of 主要な経営指標等の推移 from the same 5개년표 the profit layer already
cross-checks its FY2024/FY2025 pair against. "series" holds one value array per non-null hist_
id, index-aligned with "fiscal_years" (oldest -> newest).

Output: jp/jesr_detail.json (UTF-8, no BOM, ensure_ascii=False).
Self-check runs after the file is written; on failure the script exits 1 (file is still
written so a human can inspect it, but the caller must not treat exit 1 as success).
"""
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

JESR_DIR = Path(__file__).resolve().parent
ROOT = JESR_DIR.parent
JP_DIR = ROOT / "jp"

EXTRACTOR_SCRIPT = JESR_DIR / "extract_esr_template_samples.py"
EXTRACTED_PATH = JESR_DIR / "raw" / "fy2025_samples" / "extracted_sample_values.json"
SCHEMA_PATH = JESR_DIR / "esr_disclosure_schema.json"
RULES_PATH = JESR_DIR / "esr_aggregation_rules.json"
JESR_MASTER_PATH = JESR_DIR / "jesr_master.json"
JESR_ESR_PATH = JP_DIR / "jesr_esr.json"
OUT_PATH = JP_DIR / "jesr_detail.json"

RISK_KEYS = [
    ("rc_life", "rc_life"),
    ("rc_nonlife", "rc_nonlife"),
    ("rc_catastrophe", "rc_catastrophe"),
    ("rc_market", "rc_market"),
    ("rc_credit", "rc_credit"),
    ("rc_operational", "rc_operational"),
    ("diversification_effect", "rc_diversification"),
    ("rc_pre_tax", "rc_pre_tax"),
    ("tax_effect", "rc_tax_effect"),
    ("rc_post_tax", "rc_post_tax"),
]
MARKET_SUB_KEYS = [
    "rc_mkt_interest", "rc_mkt_spread", "rc_mkt_equity",
    "rc_mkt_property", "rc_mkt_fx", "rc_mkt_concentration",
]

LABEL_JA_DISPLAY_OVERRIDES = {
    "pl_investment_pl": "資産運用損益",
    "hist_combined_ratio_pct": "合算率（正味損害率＋正味事業費率）",
    "hist_smr_old_pct": "ソルベンシー・マージン比率（旧基準、FY2024まで）",
    "hist_esr_pct": "ESR（新基準・経済価値ベース、FY2025から）",
}

# profit layer (2026-09-12): id groupings by schema `table` tag.
PROFIT_META_TABLE = "profit:meta"
PROFIT_RATIO_TABLE = "profit:ratio"           # nonlife 損害率/事業費率/合算率
PROFIT_CORE_TABLES = {"profit:core", "profit:three"}  # life 基礎利益 decomposition + 三利源

# --- capital_tree / risk_tree (2026-09-13 ticket 20260913T0005Z) ---------------
# Pure parent-link preorder walk over the `esr` layer -- sign/is_total/aggregation
# are derived from the schema's own `parent`/`formula` fields so designer never has
# to parse a formula string. See build_tree() for the inclusion/tolerance rules.
SIGN_NUM = {"+": 1, "-": -1, "=": 1}


def _parse_child_sign(parent_formula, child_id):
    """Sign of `child_id` inside `parent_formula` ("- tier1_adjustments" -> "-"),
    default "+" when the id has no explicit leading sign (first term after "=") or
    the parent formula only describes its children in prose (e.g. rc_life's
    "sqrt(x^T R x) of rc_life_* subs" -- correlation aggregation, no offsetting)."""
    if not parent_formula:
        return "+"
    m = re.search(r"([+-])\s*" + re.escape(child_id) + r"\b", parent_formula)
    return m.group(1) if m else "+"


def _is_correlated_formula(formula):
    """告示74/75 correlation aggregation (sqrt of a quadratic form, or a disclosed
    total that is only required to be <= the naive sum of its subs) -- ticket calls
    these out for aggregation:"correlated" + a simple_sum/diversification_within
    check instead of an equality check."""
    return bool(formula) and ("<=" in formula or "sqrt" in formula)


def build_tree(root_id, merged, items_by_id, children_map):
    """Preorder-flatten the schema's parent-linked tree rooted at `root_id` (e.g.
    eligible_capital, rc_pre_tax) into the ticket's row format.

    Inclusion: a leaf (no schema children) is dropped when its value is null; an
    intermediate node (has schema children) is dropped only when its OWN value is
    null AND none of its children survived filtering (an empty container is not
    shown). A node whose own value is null but which HAS surviving children is
    still shown (label row only, value null) -- not observed in the FY2025 2-company
    sample but kept for robustness.

    is_total is structural (schema children exist) rather than formula-presence:
    three schema items in the capital tree (tier1_ni_capital_surplus/aoci/
    ev_adjustment) carry a real `formula` but it is an alias into the EBS/BS tree
    ("== ebs_..."), not a same-tree aggregation -- they are plain leaves here, which
    this structural rule gets right without a separate alias-formula special case
    (this also covers tier1_ni_retained_earnings, whose formula similarly points at
    EBS ids outside this tree).

    check.tol = max(1, n) where n = number of same-tree children actually summed --
    matches the extractor's own per-check tolerances (e.g. C12_rc_pre_tax notes
    "tol = n terms; each term truncated" for the 9-term rc_pre_tax formula: FY2025
    au/meiji both reproduce within n but not within a flat +/-1). A fixed +/-1 for
    every node (as a literal reading of the ticket's capital_tree wording would
    imply) fails the 9-term risk root for both companies; this is documented in the
    inbox answer.
    """

    def visit(node_id, depth, sign):
        item = items_by_id[node_id]
        value = merged.get(node_id)
        child_ids = children_map.get(node_id, [])
        child_subtrees = []
        term_summaries = []  # (sign_char, value) per surviving immediate child
        for cid in child_ids:
            csign = _parse_child_sign(item.get("formula"), cid)
            sub = visit(cid, depth + 1, csign)
            if sub is None:
                continue
            child_subtrees.append(sub)
            term_summaries.append((csign, sub[0]["value"]))

        if value is None and not child_subtrees:
            return None  # null leaf, or an all-null intermediate container

        is_total = bool(child_ids)
        row = {
            "id": node_id,
            "label_ja": item["labels_ja"][0] if item.get("labels_ja") else None,
            "depth": depth,
            "sign": sign,
            "value": value,
            "is_total": is_total,
        }

        usable_terms = [(s, v) for (s, v) in term_summaries if v is not None]
        if is_total and usable_terms:
            rhs = sum(SIGN_NUM[s] * v for s, v in usable_terms)
            if _is_correlated_formula(item.get("formula")):
                row["aggregation"] = "correlated"
                row["check"] = {
                    "simple_sum": rhs,
                    "disclosed": value,
                    "diversification_within": (rhs - value) if value is not None else None,
                }
            else:
                tol = max(1, len(usable_terms))
                row["check"] = {
                    "lhs": value,
                    "rhs": rhs,
                    "tol": tol,
                    "ok": value is not None and abs(value - rhs) <= tol,
                }

        rows = [row]
        for sub in child_subtrees:
            rows.extend(sub)
        return rows

    return visit(root_id, 0, "=") or []


# --- profit_flow (2026-09-13 ticket 20260913T0005Z) -----------------------------
# Fixed, owner-picked flow of profit-layer ids per sector -- NOT derived from
# schema parent/formula (every profit:* item has parent=None; the schema does not
# encode a P&L flow shape). Entries are (id, sign, label_override, derived).
# owner 2026-09-13 (2): 正味収入保険料/正味支払保険金 두 줄 대신 상대방 기준 두 블록 —
#   元受収支   = 元受正味保険料(除く収入積立保険料) − 元受正味保険金
#   再保険収支 = (受再正味保険料 − 受再正味保険金) − 支払再保険料 + 回収再保険金 + 出再保険手数料
# 受再는 사실상 出再 재원(자배책·지진 풀)이라 出再와 한 블록. 出再保険手数料(재보험자→출재사)는 손익계산서에서
# 諸手数料及び集金費 순액 안에 숨어 있으므로 여기서 꺼내 재보험 블록에 넣고, 사업비 행은 총액(支払諸手数料及び集金費)으로.
# 두 블록 − 損害調査費 − 支払諸手数料 − 営業費 ± その他(差引) = 保険引受利益 이 항상 닫히도록 その他 는 잔차(derived).
# (종전 pl_underwriting_other=その他収支 만으로는 積立保険料·満期返戻金·準備金繰入戻入이 빠져 5사 전부 underwriting_ok=False 였다.)
NONLIFE_PROFIT_FLOW = [
    ("pf_direct_balance", "=", "元受収支", True),
    ("pf_reins_balance", "±", "再保険収支", True),
    ("pl_loss_adjustment_expenses", "-", None, False),
    ("pf_commissions_row", "-", None, True),
    ("pl_uw_operating_general_admin", "-", None, False),
    ("pf_uw_other_residual", "±", "その他収支(積立保険・準備金繰入戻入等)", True),
    ("pl_underwriting_profit", "=", None, False),
    # schema label for this id is the yield table's "合計" row -- meaningless as a flow-row caption, so the
    # published label is fixed here (the working-tree jesr_detail.json already carried it by hand, 2026-09-13)
    ("pl_investment_pl", "+", "資産運用損益", False),
    ("pl_other_ordinary", "±", "その他経常損益", True),
    ("pl_ordinary_profit", "=", None, False),
    ("pl_extraordinary_net", "±", "特別損益", True),
    ("pl_income_taxes", "-", None, False),
    ("pl_net_income", "=", None, False),
]

LIFE_PROFIT_FLOW = [
    ("pl_premium_income", "=", None, False),
    ("pl_interest_margin", "+", None, False),
    ("pl_mortality_margin", "+", None, False),
    ("pl_expense_margin", "+", None, False),
    ("pl_core_profit", "=", None, False),
    ("pl_capital_gains", "+", None, False),
    ("pl_extraordinary_pl", "±", None, False),
    ("pl_ordinary_profit", "=", None, False),
    ("pl_extraordinary_net", "±", "特別損益", True),
    ("pl_policyholder_dividend_provision", "-", None, False),   # 契約者(社員)配当準備金繰入額 — 第一生命 등 배당 있는 생보
    ("pl_income_taxes", "-", None, False),
    ("pl_net_income", "=", None, False),
]


def _pair(values, pid, period):
    v = values.get(pid)
    return v.get(period) if isinstance(v, dict) else None


def _deposit(profit_raw, period):
    """収入積立保険料 that sits inside pl_gross_premiums_written (TMNF/Sompo 元受 표가 含む収入積立保険料) — 0 otherwise."""
    adj = (profit_raw.get("adjustments") or {}).get("deposit_premium_in_gross") or {}
    return adj.get(period)


def _sum_or_none(terms):
    """terms: [(value, sign)] -> signed sum; None if any value is None."""
    tot = 0
    for v, sg in terms:
        if v is None:
            return None
        tot += v if sg == "+" else -v
    return tot


def _block_parts(values, profit_raw, pid, period):
    """(value, parts) for the two balance blocks. parts = [{id,label_ja,sign,value}] (value for `period`)."""
    g = lambda i: _pair(values, i, period)
    if pid == "pf_direct_balance":
        dep = _deposit(profit_raw, period)
        parts = [("pl_gross_premiums_written", "元受正味保険料", "+", g("pl_gross_premiums_written"))]
        if dep is not None:
            parts.append(("pf_deposit_premiums", "うち収入積立保険料(控除)", "-", dep))
        parts.append(("pl_gross_claims_paid", "元受正味保険金", "-", g("pl_gross_claims_paid")))
    elif pid == "pf_reins_balance":
        parts = [("pl_assumed_premiums", "受再正味保険料", "+", g("pl_assumed_premiums")),
                 ("pl_assumed_claims", "受再正味保険金", "-", g("pl_assumed_claims")),
                 ("pl_ceded_premiums", "支払再保険料", "-", g("pl_ceded_premiums")),
                 ("pl_recovered_reinsurance_claims", "回収再保険金", "+", g("pl_recovered_reinsurance_claims"))]
        # 出再保険手数料 is a single-year note → prev None → the block's prev is None too (no silent partial sums)
        if _pair(values, "pl_ceded_commission", "cur") is not None:
            parts.append(("pl_ceded_commission", "出再保険手数料", "+", g("pl_ceded_commission")))
    else:
        raise ValueError(pid)
    return _sum_or_none([(v, sg) for _, _, sg, v in parts]), parts


def _derived_pair(pid, values, period, profit_raw=None):
    if pid in ("pf_direct_balance", "pf_reins_balance"):
        return _block_parts(values, profit_raw or {}, pid, period)[0]
    if pid == "pf_commissions_row":
        # gross (支払諸手数料及び集金費) when the note was captured, else the P&L net figure
        if _pair(values, "pl_ceded_commission", "cur") is not None:
            net, cc = _pair(values, "pl_commissions_collection", period), _pair(values, "pl_ceded_commission", period)
            return None if None in (net, cc) else net + cc
        return _pair(values, "pl_commissions_collection", period)
    if pid == "pf_uw_other_residual":
        uw = _pair(values, "pl_underwriting_profit", period)
        terms = [(_derived_pair("pf_direct_balance", values, period, profit_raw), "+"),
                 (_derived_pair("pf_reins_balance", values, period, profit_raw), "+"),
                 (_pair(values, "pl_loss_adjustment_expenses", period), "-"),
                 (_derived_pair("pf_commissions_row", values, period, profit_raw), "-"),
                 (_pair(values, "pl_uw_operating_general_admin", period), "-")]
        base = _sum_or_none(terms)
        return None if None in (uw, base) else uw - base
    if pid == "pl_other_ordinary":
        op = _pair(values, "pl_ordinary_profit", period)
        up = _pair(values, "pl_underwriting_profit", period)
        inv = _pair(values, "pl_investment_pl", period)
        if None in (op, up, inv):
            return None
        return op - up - inv
    if pid == "pl_extraordinary_net":
        g = _pair(values, "pl_extraordinary_gains", period)
        l = _pair(values, "pl_extraordinary_losses", period)
        if None in (g, l):
            return None
        return g - l
    raise ValueError(f"no derivation rule for {pid}")


def _tol_close(a, b, tol=1):
    return a is not None and b is not None and abs(a - b) <= tol


def _period_value(pid, values, period, profit_raw=None):
    if pid in ("pl_other_ordinary", "pl_extraordinary_net", "pf_direct_balance", "pf_reins_balance",
               "pf_commissions_row", "pf_uw_other_residual"):
        return _derived_pair(pid, values, period, profit_raw)
    return _pair(values, pid, period)


def _reconstruction_check(values, terms_plus, terms_minus, total_id, tol=1):
    """checks dict helper: total_id vs sum(terms_plus) - sum(terms_minus), summing
    only the terms that are actually present -- same "표시된 행만으로 재현되는지"
    philosophy as build_tree()'s check (a term missing from the selected flow is
    treated as a 0 contribution to the reconstruction, not as "can't check at all";
    it's what's NOT in terms_plus/terms_minus at all -- e.g. a P&L line the schema
    never captured -- that makes a check legitimately fail, and that failure is
    real, reportable information, not a bug).
    True only if every period with a present total_id (and >=1 present term) holds
    within tol; None if no period is checkable at all."""
    results = []
    for period in ("cur", "prev"):
        lhs = _period_value(total_id, values, period)
        if lhs is None:
            continue
        rhs, any_term = 0, False
        for pid in terms_plus:
            v = _period_value(pid, values, period)
            if v is not None:
                rhs += v
                any_term = True
        for pid in terms_minus:
            v = _period_value(pid, values, period)
            if v is not None:
                rhs -= v
                any_term = True
        if not any_term:
            continue
        results.append(_tol_close(lhs, rhs, tol))
    if not results:
        return None
    return all(results)


def build_profit_flow(profit_raw, items_by_id, sector):
    """Assemble the fixed profit_flow rows + checks for one company (2026-09-13
    ticket). Returns None if the company's profit layer has no values at all
    (status "not_obtained") -- nothing to show."""
    values = profit_raw.get("values") or {}
    if not values:
        return None

    spec = LIFE_PROFIT_FLOW if sector == "life" else NONLIFE_PROFIT_FLOW
    rows = []
    missing = []
    for pid, sign, label_override, derived in spec:
        if derived:
            cur = _derived_pair(pid, values, "cur", profit_raw)
            prev = _derived_pair(pid, values, "prev", profit_raw)
        else:
            cur = _pair(values, pid, "cur")
            prev = _pair(values, pid, "prev")
        if cur is None and prev is None:
            missing.append(pid)
            continue
        it = items_by_id.get(pid)
        label = label_override or (it["labels_ja"][0] if it and it.get("labels_ja") else pid)
        if pid == "pf_commissions_row":
            label = "支払諸手数料及び集金費" if _pair(values, "pl_ceded_commission", "cur") is not None else "諸手数料及び集金費"
        row = {
            "id": pid,
            "label_ja": label,
            "sign": sign,
            "cur": cur,
            "prev": prev,
            "derived": derived,
        }
        if pid in ("pf_direct_balance", "pf_reins_balance"):
            pc, pp = _block_parts(values, profit_raw, pid, "cur")[1], _block_parts(values, profit_raw, pid, "prev")[1]
            row["parts"] = [{"id": i, "label_ja": lab, "sign": sg, "cur": v, "prev": pp[k][3]} for k, (i, lab, sg, v) in enumerate(pc)]
        rows.append(row)

    if sector == "life":
        checks = {
            "underwriting_ok": None,  # not applicable to the life flow shape
            "ordinary_ok": _reconstruction_check(
                values, ["pl_core_profit", "pl_capital_gains", "pl_extraordinary_pl"], [], "pl_ordinary_profit"
            ),
            "net_ok": _reconstruction_check(values, ["pl_ordinary_profit", "pl_extraordinary_net"], ["pl_policyholder_dividend_provision", "pl_income_taxes"], "pl_net_income"),
        }
    else:
        # underwriting flow closes by construction (その他 is the residual) → check the disclosed identities instead:
        # 正味 = 元受 + 受再 − 出再 (− 収入積立保険料 when the 元受 table includes it) for premiums and claims.
        dep_c, dep_p = _deposit(profit_raw, "cur"), _deposit(profit_raw, "prev")
        def _bridge_ok(net_id, gross_id, assumed_id, minus_id, dep_by_period):
            res = []
            for period, dep in (("cur", dep_by_period[0]), ("prev", dep_by_period[1])):
                lhs = _pair(values, net_id, period)
                rhs = _sum_or_none([(_pair(values, gross_id, period), "+"), (_pair(values, assumed_id, period), "+"),
                                    (_pair(values, minus_id, period), "-")])
                if lhs is None or rhs is None:
                    continue
                res.append(_tol_close(lhs, rhs - (dep or 0), 1))
            return all(res) if res else None
        checks = {
            "premium_bridge_ok": _bridge_ok("pl_net_premiums_written", "pl_gross_premiums_written", "pl_assumed_premiums", "pl_ceded_premiums", (dep_c, dep_p)),
            "claims_bridge_ok": _bridge_ok("pl_net_claims_paid", "pl_gross_claims_paid", "pl_assumed_claims", "pl_recovered_reinsurance_claims", (None, None)),
            "commission_note_ok": (None if _pair(values, "pl_ceded_commission", "cur") is None else
                                   _tol_close(_pair(values, "pl_commissions_gross", "cur"),
                                              _sum_or_none([(_pair(values, "pl_commissions_collection", "cur"), "+"), (_pair(values, "pl_ceded_commission", "cur"), "+")]), 1)),
            "underwriting_ok": True,   # residual row makes the flow close by construction (kept for the page's badge)
            "ordinary_ok": _reconstruction_check(
                values, ["pl_underwriting_profit", "pl_investment_pl", "pl_other_ordinary"], [], "pl_ordinary_profit"
            ),
            "net_ok": _reconstruction_check(
                values, ["pl_ordinary_profit", "pl_extraordinary_net"], ["pl_income_taxes"], "pl_net_income"
            ),
        }

    return {"sector": sector, "rows": rows, "missing": missing, "checks": checks}


def ensure_extracted():
    if EXTRACTED_PATH.exists():
        return
    print(f"[build_jesr_detail_json] {EXTRACTED_PATH} missing -- running extractor first")
    result = subprocess.run([sys.executable, str(EXTRACTOR_SCRIPT)], cwd=str(ROOT))
    if not EXTRACTED_PATH.exists():
        raise SystemExit(
            f"extractor exited {result.returncode} and still did not produce {EXTRACTED_PATH}"
        )


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def r1(x):
    return round(x, 1) if isinstance(x, (int, float)) else x


LIFE_CORE_PATH = SCHEMA_PATH.parent / "raw" / "fy2025_samples" / "life_core_history.json"

# core_history ids are not schema items (life sample values come from J-ESR/extract_life_core_history.py)
CORE_HISTORY_LABELS = {
    "hist_core_profit": {"ja": "基礎利益", "ko": "기초이익(단체)", "unit": "JPY_100million"},
    "hist_core_profit_group": {"ja": "グループ基礎利益", "ko": "기초이익(그룹 합산)", "unit": "JPY_100million"},
    "hist_interest_margin": {"ja": "利差損益", "ko": "이차손익(三利源)", "unit": "JPY_100million"},
    "hist_mortality_margin": {"ja": "危険差損益", "ko": "위험차손익(三利源)", "unit": "JPY_100million"},
    "hist_expense_margin": {"ja": "費差損益", "ko": "비차손익(三利源)", "unit": "JPY_100million"},
    "hist_insurance_margin": {"ja": "保険関係損益", "ko": "보험관계손익(危険差+費差 합산 공시형)", "unit": "JPY_100million"},
    "hist_operating_profit": {"ja": "業務利益", "ko": "업무이익(기초이익에서 표준책임준비금 적립 영향 제외)", "unit": "JPY_100million"},
    "hist_investment_margin": {"ja": "運用関係損益", "ko": "운용관계손익", "unit": "JPY_100million"},
}


def build_by_line_block(byline_raw, lob_lines):
    """layer by_line (2026-09-13 ticket 20260913T0400Z) — 損保 種目別 표 3개. Published shape:
    {"unit", "lines":[code...], "labels_ja":{code: 原文}, "items":{lob_id:{code:{prev,cur}}}, "checks":{...}}.
    Only lob_* ids (never the private _loss_ratio_from_claims_table cross-ref)."""
    values = byline_raw.get("values") or {}
    items = {k: v for k, v in values.items() if k.startswith("lob_") and isinstance(v, dict)}
    checks = byline_raw.get("checks") or []
    gate = [c for c in checks if c.get("gate", True)]
    return {
        "unit": "JPY_million",
        "lines": [c for c, _ja in lob_lines],
        "labels_ja": {c: ja for c, ja in lob_lines},
        "items": items,
        "checks": {"pass": sum(1 for c in gate if c["pass"]), "total": len(gate),
                   "failed": [c["id"] for c in gate if not c["pass"]],
                   "info_failed": [c["id"] for c in checks if not c.get("gate", True) and not c["pass"]]},
    }


def build_core_history_block(entry, years):
    """layer core_history (life): {fiscal_years, unit, series:{id:[v...]}, labels_ja, three_source, source}."""
    series = {}
    for hid, per_year in (entry.get("values") or {}).items():
        if isinstance(per_year, dict) and any(per_year.get(y) is not None for y in years):
            series[hid] = [per_year.get(y) for y in years]
    return {
        "fiscal_years": years,
        "unit": entry.get("unit_disclosed") or "JPY_100million",
        "series": series,
        "labels_ja": entry.get("labels_ja") or {},
        "pages": entry.get("pages") or {},
        "three_source": entry.get("three_source"),
        "status": "extracted" if series else "not_acquired",
        "notes": entry.get("notes") or [],
    }


BS_PATH = SCHEMA_PATH.parent / "raw" / "fy2025_samples" / "extracted_bs_values.json"

# layer bs (ticket 20260913T1300Z) — J-GAAP 貸借対照表 요약, ids are not schema items (J-ESR/extract_bs.py)
BS_LABELS = {
    "bs_assets_total": {"ja": "資産合計", "ko": "자산 합계"},
    "bs_cash": {"ja": "現金及び預貯金", "ko": "현금 및 예치금"},
    "bs_securities": {"ja": "有価証券", "ko": "유가증권"},
    "bs_loans": {"ja": "貸付金", "ko": "대출금"},
    "bs_tangible": {"ja": "有形固定資産", "ko": "유형고정자산"},
    "bs_other_assets": {"ja": "その他資産", "ko": "기타자산(잔차: 자산합계 − 위 4행)"},
    "bs_liabilities_total": {"ja": "負債合計", "ko": "부채 합계"},
    "bs_policy_reserves_total": {"ja": "保険契約準備金", "ko": "보험계약준비금"},
    "bs_outstanding_claims": {"ja": "支払備金", "ko": "지급비금"},
    "bs_policy_reserves": {"ja": "責任準備金", "ko": "책임준비금"},
    "bs_policyholder_dividend_reserve": {"ja": "契約者配当準備金", "ko": "계약자(사원)배당준비금"},
    "bs_bonds": {"ja": "社債", "ko": "사채"},
    "bs_other_liabilities": {"ja": "その他負債", "ko": "기타부채(잔차: 부채합계 − 보험계약준비금 − 사채)"},
    "bs_net_assets_total": {"ja": "純資産合計", "ko": "순자산 합계"},
    "bs_capital_and_surplus": {"ja": "資本金・資本剰余金", "ko": "자본금·자본잉여금(상호회사는 기금·기금상각적립금)"},
    "bs_retained_earnings": {"ja": "利益剰余金", "ko": "이익잉여금(상호회사는 잉여금)"},
    "bs_valuation_diff": {"ja": "その他有価証券評価差額金", "ko": "기타유가증권 평가차액금(부호 그대로)"},
    "bs_other_equity": {"ja": "その他(純資産)", "ko": "기타 순자산(잔차: 이연헤지손익·토지재평가차액금·자기주식 등, 음수 가능)"},
}


def build_bs_block(entry):
    """layer bs: {status, as_of, unit, scope, source_doc, pages, tree, checks, notes}. tree rows share the
    capital_tree shape (id/label_ja/depth/sign/cur/prev/parent/derived) so the page's treeRows() is reused."""
    if not entry or entry.get("status") != "extracted":
        return {"status": "not_obtained", "scope": (entry or {}).get("scope"), "source_doc": (entry or {}).get("source_doc"),
                "tree": [], "checks": {}, "notes": (entry or {}).get("notes") or []}
    return {
        "status": "extracted", "as_of": entry.get("as_of"), "unit": entry.get("unit"), "unit_disclosed": entry.get("unit_disclosed"),
        "scope": entry.get("scope"), "source_doc": entry.get("source_doc"), "doc_type": entry.get("doc_type"),
        "pages": entry.get("pages") or {}, "tree": entry.get("tree") or [], "checks": entry.get("checks") or {},
        "notes": entry.get("notes") or [],
    }


def build_history_block(history_raw):
    """Assemble the history block (2026-09-12 ticket 20260912T1440Z) — 主要な経営指標等の推移
    5개년표. Extraction stores each id as a {fiscal_year: value} dict (schema/self-describing);
    the published block re-shapes to a fiscal_years array + parallel value arrays per the ticket's
    contract (`{"unit":..., "fiscal_years":[...], "series":{"<hist_id>":[v,...]}}`)."""
    values = history_raw.get("values") or {}
    years = history_raw.get("fiscal_years") or ["FY2021", "FY2022", "FY2023", "FY2024", "FY2025"]
    series = {}
    for hid, per_year in values.items():
        if not isinstance(per_year, dict):
            continue  # N/A_SECTOR (life-only ids) or not extracted
        if all(per_year.get(y) is None for y in years):
            continue  # non-null 만 (profit 블록과 같은 관례)
        series[hid] = [per_year.get(y) for y in years]
    return {"fiscal_years": years, "unit": "JPY_million", "series": series}


def build_profit_block(profit_raw, items_by_id):
    """Assemble the profit block for one company from its extracted profit.values/meta.

    items_by_id: schema id -> schema item dict (for the `table` tag lookup).
    """
    values = profit_raw.get("values") or {}
    meta = profit_raw.get("meta") or {}
    source_doc = meta.get("profit_source_doc")
    status = "not_obtained" if isinstance(source_doc, str) and source_doc.startswith("NOT_ACQUIRED") else "extracted"

    items = {}
    ratios = {}
    core = {}
    for pid, val in values.items():
        it = items_by_id.get(pid)
        if it is None or it.get("table") == PROFIT_META_TABLE:
            continue  # accounting_basis/ifrs17_applied/evidence/source_doc are top-level fields, not items
        if not isinstance(val, dict):
            continue
        cur = val.get("cur")
        prev = val.get("prev")
        if cur is None and prev is None:
            continue  # non-null 만 (2026-09-12 ticket)
        entry = {"cur": cur, "prev": prev}
        items[pid] = entry
        table = it.get("table")
        if table == PROFIT_RATIO_TABLE:
            ratios[pid] = entry
        elif table in PROFIT_CORE_TABLES:
            core[pid] = entry

    return {
        "accounting_basis": meta.get("accounting_basis"),
        "ifrs17_applied": meta.get("ifrs17_applied"),
        "evidence": meta.get("accounting_basis_evidence"),
        "source_doc": source_doc,
        "unit": "JPY_million",
        "items": items,
        "ratios": ratios,
        "core": core,
        "adjustments": profit_raw.get("adjustments") or {},
        "status": status,
    }


def build(extracted, schema, jesr_master, jesr_esr):
    labels = {}
    bs_by_id = (load_json(BS_PATH).get("companies") or {}) if BS_PATH.exists() else {}
    items_by_id = {}
    for it in schema["items"]:
        items_by_id[it["id"]] = it
        ja = it["labels_ja"][0] if it.get("labels_ja") else None
        labels[it["id"]] = {
            "ja": ja,
            "ko": it.get("ko"),
            "unit": it.get("unit"),
            "kics_item_ref": it.get("kics_item_ref"),
            "pl_item_ref": it.get("pl_item_ref"),
        }

    # Display labels that were fixed by hand in the published JSON (commit e67bc36 and the 2026-09-13
    # working tree) but never in the schema: the schema's labels_ja[0] is the extraction anchor
    # (e.g. the yield table's "合計" row, the shared SMR/ESR row caption), not a screen caption.
    # Pinned here so a rebuild reproduces the published labels instead of silently reverting them.
    for pid, ja in LABEL_JA_DISPLAY_OVERRIDES.items():
        if pid in labels:
            labels[pid]["ja"] = ja

    # 2026-09-13: derived ids that only exist inside profit_flow (not schema items,
    # so build_profit_block's schema-driven label loop above never sees them) --
    # add their labels here per the ticket ("_meta.labels 에 파생 id 라벨 추가").
    labels["pl_other_ordinary"] = {
        "ja": "その他経常損益", "ko": "기타 경상손익(파생: 경상이익-引受利益-운용손익)",
        "unit": "JPY_million", "kics_item_ref": None, "pl_item_ref": None,
    }
    labels["pl_extraordinary_net"] = {
        "ja": "特別損益", "ko": "특별손익 순액(파생: 특별이익-특별손실)",
        "unit": "JPY_million", "kics_item_ref": None, "pl_item_ref": None,
    }
    # owner 2026-09-13 (2): 元受/再保険 두 블록 + 잔차 행 (build_profit_flow NONLIFE_PROFIT_FLOW 주석 참조)
    for pid, ja, ko in [
        ("pf_direct_balance", "元受収支", "원수 수지(파생: 원수정미보험료(적립보험료 제외) − 원수정미보험금)"),
        ("pf_reins_balance", "再保険収支", "재보험 수지(파생: 수재보험료 − 수재보험금 − 출재보험료 + 회수재보험금 + 출재보험수수료; 전기는 출재보험수수료 미취득이라 공란)"),
        ("pf_deposit_premiums", "うち収入積立保険料(控除)", "원수정미보험료에 포함된 적립보험료(정미수입보험료 산정 시 차감)"),
        ("pf_commissions_row", "支払諸手数料及び集金費", "지급제수수료 및 집금비(총액 = 손익계산서 순액 + 출재보험수수료; 注記 없으면 순액)"),
        ("pf_uw_other_residual", "その他収支(積立保険・準備金繰入戻入等)", "기타 수지(잔차: 보험인수이익 − 위 행 합계; 적립보험료·만기환급금·준비금 전입환입·기타수지 포함)"),
    ]:
        labels[pid] = {"ja": ja, "ko": ko, "unit": "JPY_million", "kics_item_ref": None, "pl_item_ref": None}

    for bid, lab in BS_LABELS.items():
        labels.setdefault(bid, {**lab, "unit": "JPY_million", "kics_item_ref": None, "pl_item_ref": None})
    for hid, lab in CORE_HISTORY_LABELS.items():
        labels.setdefault(hid, {**lab, "kics_item_ref": None, "pl_item_ref": None})
    lob_lines = []
    for it in schema["items"]:
        if it.get("layer") == "by_line" and it.get("line_codes"):
            ja_tail = it["labels_ja"][-len(it["line_codes"]):]
            lob_lines = list(zip(it["line_codes"], ja_tail))
            break

    # capital_tree / risk_tree (2026-09-13): schema-structural parent -> children
    # map over the esr layer, built once (shared by every company's tree walk).
    children_map = {}
    for it in schema["items"]:
        if it.get("layer") == "esr" and it.get("parent"):
            children_map.setdefault(it["parent"], []).append(it["id"])

    master_by_en = {r["company_en"]: r for r in jesr_master.get("records", [])}
    public_by_en = {r["company_en"]: r for r in jesr_esr.get("records", [])}
    for r in jesr_esr.get("_meta", {}).get("excluded_subsidiaries", []):
        public_by_en.setdefault(r["company_en"], r)

    companies_out = []
    life_entries, life_years = {}, ["FY2021", "FY2022", "FY2023", "FY2024", "FY2025"]
    if LIFE_CORE_PATH.exists():
        _life = load_json(LIFE_CORE_PATH)
        life_entries = _life.get("companies") or {}
        life_years = _life.get("fiscal_years") or life_years
    for cid, comp in extracted["companies"].items():
        status = comp.get("census", {}).get("status")
        # 2026-09-13 (ticket 20260913T0330Z): ESR-not-yet companies are included when every OTHER
        # layer is there (profit extracted + history layer) -- the big-3 non-life main volumes.
        # nnlife (not_yet, no history layer) stays out.
        if status == "posted":
            esr_status = "posted"
        elif status == "not_yet" and "history" in comp.get("layers", []) and comp.get("profit", {}).get("values"):
            esr_status = "not_yet"
        elif comp.get("sector") == "life" and comp.get("profit", {}).get("values"):
            # 2026-09-13 owner: 생보도 損益·基礎利益 층이 추출되면 상세 회사로(NN Life·第一生命). ESR 은 미공표(not_yet/not_found).
            # core_history 는 아래 life_core_only 경로 대신 여기서 붙인다(LIFE_CORE_PATH 항목이 있으면).
            esr_status = status if status in ("not_yet", "not_found") else "not_found"
        else:
            continue
        esr = comp.get("esr") if esr_status == "posted" else None
        values = esr["values"] if esr else {}
        method = esr["method"] if esr else {}
        merged = {**values, **method}
        summ = extracted["summary"][cid]

        company_en = comp["company_en"]
        src = master_by_en.get(company_en, {})
        if not src and esr_status == "not_yet":
            src = {"source_url": comp.get("source_url"), "doc_type": comp.get("source_doc_type"), "doc_date": None, "preliminary": None}

        headline = {
            "eligible_capital": values.get("eligible_capital"),
            "required_capital": values.get("required_capital"),
            "esr_pct": values.get("esr_pct"),
            "preliminary": src.get("preliminary"),
        }

        capital = {
            it["id"]: merged.get(it["id"])
            for it in schema["items"]
            if it["table"] == "T2" and merged.get(it["id"]) is not None
        }

        risk = {out_key: merged.get(src_key) for out_key, src_key in RISK_KEYS}
        market_sub = {k: merged.get(k) for k in MARKET_SUB_KEYS}

        sensitivity = []
        sens = (esr.get("sensitivity") if esr else None) or {}
        levels = sens.get("levels", {}).get("esr_pct", {})
        diffs = sens.get("diffs", {}).get("esr_pct", {})
        for scen in sens.get("scenarios", []):
            if scen == "base":
                continue
            lvl = levels.get(scen)
            dpp = diffs.get(scen)
            if lvl is None or dpp is None:
                continue  # omitted/undisclosed scenario -- leave out rather than guess
            sid = f"sens_{scen}_esr_pct"
            sitem = items_by_id.get(sid)
            sensitivity.append({
                "id": sid,
                "label_ja": sitem["labels_ja"][0] if sitem else scen,
                "esr_pct": r1(lvl),
                "delta_pp": r1(dpp),
            })

        deviations = []
        for chk in (esr.get("checks", []) if esr else []):
            if chk["id"] in summ.get("checks_info_failed", []):
                deviations.append({
                    "id": chk["id"],
                    "lhs": chk.get("lhs"),
                    "rhs": chk.get("rhs"),
                    "note": chk.get("note", ""),
                })

        agg_recompute = (esr.get("aggregation_recompute") if esr else None) or {}
        aggregation = {
            "top_sqrt": agg_recompute.get("top_sqrt"),
            "simple_sum": agg_recompute.get("simple_sum_ABCDE"),
            "reproduced": len(summ.get("checks_failed", [])) == 0,
            "checks_pass": summ.get("checks_pass"),
            "checks_total": summ.get("checks_total"),
            "deviations": deviations,
        }

        axes_values = comp.get("axes", {}).get("values", {})
        axes = {k: v for k, v in axes_values.items() if v is not None}

        items = {
            it["id"]: merged.get(it["id"])
            for it in schema["items"]
            if it["layer"] == "esr" and merged.get(it["id"]) is not None
        }

        profit = build_profit_block(comp.get("profit") or {}, items_by_id)
        history = build_history_block(comp.get("history") or {})
        # not_yet: no esr layer -> empty trees (never a label-only skeleton; the page shows the placeholder note instead)
        capital_tree = build_tree("eligible_capital", merged, items_by_id, children_map) if esr else []
        risk_tree = build_tree("rc_pre_tax", merged, items_by_id, children_map) if esr else []
        profit_flow = build_profit_flow(comp.get("profit") or {}, items_by_id, comp.get("sector"))
        by_line = build_by_line_block(comp["by_line"], lob_lines) if comp.get("by_line") else None

        companies_out.append({
            "id": cid,
            "company_jp": comp.get("company_jp"),
            "company_en": company_en,
            "sector": comp.get("sector"),
            "scope": comp.get("scope"),
            "as_of": comp.get("as_of"),
            "esr_status": esr_status,
            "esr_placeholder": (
                None if esr_status == "posted" else
                {"phrases": sorted({loc["phrase"] for loc in axes_values.get("esr_placeholder_locations", [])}),
                 "pages": sorted({loc["page"] for loc in axes_values.get("esr_placeholder_locations", [])}),
                 "expected": "2026-10-31"}
            ),
            "source_url": src.get("source_url"),
            "doc_type": src.get("doc_type"),
            "doc_date": src.get("doc_date"),
            "headline": headline,
            "capital": capital,
            "risk": risk,
            "market_sub": market_sub,
            "sensitivity": sensitivity,
            "aggregation": aggregation,
            "axes": axes,
            "items": items,
            "profit": profit,
            "history": history,
            "capital_tree": capital_tree,
            "risk_tree": risk_tree,
            "profit_flow": profit_flow,
            "by_line": by_line,
            "core_history": (build_core_history_block(life_entries[cid], life_years) if cid in life_entries else None),
            "bs": build_bs_block(bs_by_id.get(cid)),
        })

    # 2026-09-13 (ticket 20260913T0400Z): life insurers enter with the core_history layer only
    # (基礎利益·三利源). esr_status "life_core_only" -- no ESR/profit/history blocks are fabricated;
    # headline reuses the already-published group/solo ESR from jp/jesr_esr.json when that record exists.
    if LIFE_CORE_PATH.exists():
        life = load_json(LIFE_CORE_PATH)
        years = life.get("fiscal_years") or ["FY2021", "FY2022", "FY2023", "FY2024", "FY2025"]
        for cid, entry in life["companies"].items():
            if any(c["id"] == cid for c in companies_out):
                continue
            cen = entry["company_en"]
            pub = public_by_en.get(cen) or {}
            companies_out.append({
                "id": cid, "company_jp": entry.get("company_jp"), "company_en": cen, "sector": "life",
                "scope": entry.get("scope"), "as_of": "2026-03-31", "esr_status": "life_core_only", "esr_placeholder": None,
                "source_url": entry.get("source_url"), "doc_type": entry.get("doc_type"), "doc_date": None,
                "headline": {"eligible_capital": None, "required_capital": None, "esr_pct": pub.get("esr_pct"), "preliminary": pub.get("preliminary"),
                             "esr_scope": pub.get("esr_scope") or pub.get("scope")},
                "capital": {}, "risk": {}, "market_sub": {}, "sensitivity": {}, "aggregation": None, "axes": {}, "items": {},
                "profit": None, "history": None, "capital_tree": [], "risk_tree": [], "profit_flow": None, "by_line": None,
                "core_history": build_core_history_block(entry, years),
                "bs": build_bs_block(bs_by_id.get(cid)),
            })

    meta_src = jesr_esr.get("_meta", {})
    return {
        "_meta": {
            "as_of": meta_src.get("as_of"),
            "as_of_label_ja": meta_src.get("as_of_label_ja"),
            "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "unit": "JPY_million",
            "schema_ref": "J-ESR/esr_disclosure_schema.json",
            "rules_ref": "J-ESR/esr_aggregation_rules.json",
            "labels": labels,
            "next_update": meta_src.get("next_update"),
            "coverage": {
                "detail_total": len(companies_out),
                "esr_posted": sum(1 for c in companies_out if c["esr_status"] == "posted"),
                "esr_not_yet": sum(1 for c in companies_out if c["esr_status"] == "not_yet"),
                "life_core_only": sum(1 for c in companies_out if c["esr_status"] == "life_core_only"),
                "by_line_total": sum(1 for c in companies_out if c.get("by_line")),
                "bs_extracted": sum(1 for c in companies_out if (c.get("bs") or {}).get("status") == "extracted"),
                "posted_total": len(jesr_esr.get("records", [])),
                "census_total": meta_src.get("census", {}).get("total"),
            },
        },
        "companies": companies_out,
    }


def self_check(out, jesr_esr):
    errors = []
    companies = out["companies"]
    n_posted = sum(1 for c in companies if c.get("esr_status") == "posted")
    n_not_yet = sum(1 for c in companies if c.get("esr_status") == "not_yet")
    # 2026-09-13: not_yet 5 = 大型損保 3 + 生保 2(NN Life·第一生命 — 損益·基礎利益 층 추출, ESR 미공표)
    if n_posted != 2 or n_not_yet != 5:
        errors.append(f"expected 2 esr-posted + 5 esr-not_yet companies, got {n_posted} + {n_not_yet}")
    cov = out["_meta"]["coverage"]
    if cov.get("detail_total") != len(companies) or cov.get("esr_posted") != n_posted:
        errors.append(f"_meta.coverage inconsistent with companies: {cov}")

    public_by_en = {r["company_en"]: r for r in jesr_esr.get("records", [])}
    for r in jesr_esr.get("_meta", {}).get("excluded_subsidiaries", []):
        public_by_en.setdefault(r["company_en"], r)

    labels = out["_meta"]["labels"]

    for c in companies:
        cen = c["company_en"]
        bs = c.get("bs") or {}
        if bs.get("status") == "extracted":
            missing_bs = [r["id"] for r in bs.get("tree", []) if r["id"] not in labels]
            if missing_bs:
                errors.append(f"{cen}: bs ids missing from _meta.labels: {missing_bs}")
            ids = {r["id"] for r in bs.get("tree", [])}
            need = [t for t in ("bs_assets_total", "bs_liabilities_total", "bs_net_assets_total") if t not in ids]
            if need:
                errors.append(f"{cen}: bs totals missing: {need}")
            for k, v in (bs.get("checks") or {}).items():
                if v is False:
                    print(f"WARN {cen}: bs check {k} is False (not an error)")
        elif bs.get("status") != "not_obtained":
            errors.append(f"{cen}: bs block missing")
        if c.get("esr_status") == "life_core_only":
            ch = c.get("core_history") or {}
            if ch.get("status") == "extracted":
                missing = [k for k in ch.get("series", {}) if k not in labels]
                if missing:
                    errors.append(f"{cen}: core_history ids missing from _meta.labels: {missing}")
                if len(ch.get("fiscal_years", [])) != 5 or any(len(v) != 5 for v in ch.get("series", {}).values()):
                    errors.append(f"{cen}: core_history series must be 5 fiscal years wide")
            elif not ch.get("notes"):
                errors.append(f"{cen}: core_history not_acquired without a reason note")
            if c["headline"]["eligible_capital"] is not None or c["capital_tree"] or c["profit"] is not None:
                errors.append(f"{cen}: life_core_only must not carry esr/profit blocks")
            continue
        bl = c.get("by_line")
        if c.get("sector") == "nonlife":
            if not bl or not bl.get("items"):
                errors.append(f"{cen}: nonlife company without by_line items")
            elif bl["checks"]["failed"]:
                errors.append(f"{cen}: by_line gate checks failed: {bl['checks']['failed']}")
            else:
                missing = [k for k in bl["items"] if k not in labels]
                if missing:
                    errors.append(f"{cen}: by_line ids missing from _meta.labels: {missing}")
        if c.get("esr_status") == "not_yet":
            # 2026-09-13 (ticket 20260913T0330Z): ESR layer absent by disclosure timing (2026-10-31) --
            # headline/capital/risk must be EMPTY (never a guessed skeleton); profit/history are checked
            # exactly like a posted company (same 合算率 identity, same FY2025/FY2024 xref).
            if c["headline"]["esr_pct"] is not None or c["headline"]["eligible_capital"] is not None or c["headline"]["required_capital"] is not None:
                errors.append(f"{cen}: not_yet but headline carries ESR values {c['headline']}")
            if c["capital_tree"] or c["risk_tree"] or c["capital"] or c["items"] or c["sensitivity"]:
                errors.append(f"{cen}: not_yet but esr-layer blocks are not empty")
            if any(v is not None for v in c["risk"].values()) or any(v is not None for v in c["market_sub"].values()):
                errors.append(f"{cen}: not_yet but risk/market_sub carry values")
            ph = c.get("esr_placeholder") or {}
            if c.get("sector") != "life" and (not ph.get("phrases") or not ph.get("pages")):
                errors.append(f"{cen}: not_yet requires >=1 placeholder phrase/page from the source PDF, got {ph}")
            if not c.get("source_url") and c.get("sector") != "life":
                errors.append(f"{cen}: source_url missing")
            profit = c.get("profit") or {}
            if profit.get("status") != "extracted":
                errors.append(f"{cen}: profit.status expected 'extracted', got {profit.get('status')!r}")
            is_life = c.get("sector") == "life"
            # 생보(NN Life·第一生命, 2026-09-13): 損保 전용 항목(正味収入保険料·保険引受利益·損害率·5개년 history) 대신 基礎利益 층과 core_history 를 요구
            req_ids = ("pl_ordinary_profit", "pl_net_income", "pl_core_profit") if is_life else ("pl_ordinary_profit", "pl_net_income", "pl_underwriting_profit", "pl_net_premiums_written")
            for req in req_ids:
                if req not in profit.get("items", {}) and req not in profit.get("core", {}):
                    errors.append(f"{cen}: profit.items missing required id {req}")
            ratios = profit.get("ratios", {})
            for period in ("cur", "prev"):
                if is_life:
                    break
                loss = ratios.get("pl_loss_ratio_pct", {}).get(period)
                expense = ratios.get("pl_expense_ratio_pct", {}).get(period)
                combined = ratios.get("pl_combined_ratio_pct", {}).get(period)
                if None in (loss, expense, combined):
                    errors.append(f"{cen}: profit.ratios[{period}] missing loss/expense/combined for 合算率 check")
                elif abs((loss + expense) - combined) > 0.1 + 1e-9:
                    errors.append(f"{cen}: profit.ratios[{period}] 合算率 mismatch -- {loss}+{expense} vs {combined}")
            if is_life:
                if not ((c.get("core_history") or {}).get("series")):
                    errors.append(f"{cen}: life detail requires core_history.series")
            elif not (c.get("history") or {}).get("series"):
                errors.append(f"{cen}: history.series empty")
            pflow = c.get("profit_flow")
            if pflow is not None and pflow["checks"].get("ordinary_ok") is False:
                errors.append(f"{cen}: profit_flow ordinary_ok is False: {pflow['checks']}")
            missing_labels = [k for k in list(profit.get("items", {})) + list((c.get("history") or {}).get("series", {})) if k not in labels]
            if missing_labels:
                errors.append(f"{cen}: ids missing from _meta.labels: {missing_labels}")
            _check_history_xref(c, labels, errors)
            continue
        pub = public_by_en.get(cen)
        if pub is None:
            errors.append(f"{cen}: not found in jp/jesr_esr.json records/excluded_subsidiaries")
        elif c["headline"]["esr_pct"] != pub.get("esr_pct"):
            errors.append(
                f"{cen}: headline.esr_pct {c['headline']['esr_pct']} != "
                f"jp/jesr_esr.json {pub.get('esr_pct')}"
            )
        if c["risk"]["rc_post_tax"] != c["headline"]["required_capital"]:
            errors.append(
                f"{cen}: risk.rc_post_tax {c['risk']['rc_post_tax']} != "
                f"headline.required_capital {c['headline']['required_capital']}"
            )
        missing_labels = [k for k in c["items"].keys() if k not in labels]
        if missing_labels:
            errors.append(f"{cen}: items ids missing from _meta.labels: {missing_labels}")

        # capital_tree (2026-09-13 ticket) -- root present, is eligible_capital,
        # root check reproduces within its own declared tolerance.
        ctree = c.get("capital_tree") or []
        if not ctree or ctree[0]["id"] != "eligible_capital":
            errors.append(f"{cen}: capital_tree missing or root id != eligible_capital")
        else:
            root_chk = ctree[0].get("check")
            if not root_chk or not root_chk.get("ok"):
                errors.append(f"{cen}: capital_tree root check not ok: {root_chk}")
            tree_labels_missing = [row["id"] for row in ctree if row["id"] not in labels]
            if tree_labels_missing:
                errors.append(f"{cen}: capital_tree ids missing from _meta.labels: {tree_labels_missing}")
            depths = [row["depth"] for row in ctree]
            if depths and (min(depths) != 0 or max(depths) > 4):
                errors.append(f"{cen}: capital_tree depth out of 0..4 range: {sorted(set(depths))}")

        # risk_tree -- root present, is rc_pre_tax, reproduces rc_pre_tax = Σ대분류
        # + 운영 − 분산효과 within tol=max(1,n terms) (see build_tree docstring: a
        # flat +/-1 fails this 9-term formula for both FY2025 companies).
        rtree = c.get("risk_tree") or []
        if not rtree or rtree[0]["id"] != "rc_pre_tax":
            errors.append(f"{cen}: risk_tree missing or root id != rc_pre_tax")
        else:
            root_chk = rtree[0].get("check")
            if not root_chk or not root_chk.get("ok"):
                errors.append(f"{cen}: risk_tree root check not ok: {root_chk}")
            tree_labels_missing = [row["id"] for row in rtree if row["id"] not in labels]
            if tree_labels_missing:
                errors.append(f"{cen}: risk_tree ids missing from _meta.labels: {tree_labels_missing}")
            for row in rtree:
                if row.get("aggregation") == "correlated":
                    chk = row.get("check") or {}
                    if chk.get("simple_sum") is None or chk.get("disclosed") is None:
                        errors.append(f"{cen}: risk_tree correlated node {row['id']} missing simple_sum/disclosed")

        # profit_flow -- rows/missing partition the fixed sequence for this
        # sector, derived ids are labelled, and the tautological ordinary_ok
        # (row7+row8+row9==row10 by construction) actually holds -- if it doesn't,
        # that is a real arithmetic bug, unlike underwriting_ok/net_ok which can
        # legitimately be False/None when the source P&L has lines outside the
        # selected flow (see inbox answer).
        pflow = c.get("profit_flow")
        if pflow is not None:
            row_ids = {r["id"] for r in pflow["rows"]}
            missing_ids = set(pflow["missing"])
            if row_ids & missing_ids:
                errors.append(f"{cen}: profit_flow ids in both rows and missing: {row_ids & missing_ids}")
            missing_from_meta = [i for i in row_ids if i not in labels]
            if missing_from_meta:
                errors.append(f"{cen}: profit_flow row ids missing from _meta.labels: {missing_from_meta}")
            if pflow["checks"].get("ordinary_ok") is False:
                errors.append(f"{cen}: profit_flow ordinary_ok is False (expected tautological True/None): {pflow['checks']}")
        # unit passthrough guard: no JPY_million -> JPY_100million (or any other) conversion
        # may have been applied anywhere in this builder.
        if c["items"].get("eligible_capital") != c["headline"]["eligible_capital"]:
            errors.append(
                f"{cen}: unit/passthrough mismatch -- items.eligible_capital "
                f"{c['items'].get('eligible_capital')} != headline.eligible_capital "
                f"{c['headline']['eligible_capital']}"
            )

        # profit layer (2026-09-12 ticket)
        profit = c.get("profit") or {}
        missing_profit_labels = [
            k for k in list(profit.get("items", {})) + list(profit.get("ratios", {})) + list(profit.get("core", {}))
            if k not in labels
        ]
        if missing_profit_labels:
            errors.append(f"{cen}: profit ids missing from _meta.labels: {missing_profit_labels}")

        if c["id"] == "au_nonlife":
            if profit.get("status") != "extracted":
                errors.append(f"{cen}: profit.status expected 'extracted', got {profit.get('status')!r}")
            for req in ("pl_ordinary_profit", "pl_net_income"):
                if req not in profit.get("items", {}):
                    errors.append(f"{cen}: profit.items missing required id {req}")
            ratios = profit.get("ratios", {})
            for period in ("cur", "prev"):
                loss = ratios.get("pl_loss_ratio_pct", {}).get(period)
                expense = ratios.get("pl_expense_ratio_pct", {}).get(period)
                combined = ratios.get("pl_combined_ratio_pct", {}).get(period)
                if None in (loss, expense, combined):
                    errors.append(f"{cen}: profit.ratios[{period}] missing loss/expense/combined for 合算率 check")
                elif abs((loss + expense) - combined) > 0.1 + 1e-9:
                    errors.append(
                        f"{cen}: profit.ratios[{period}] 合算率 mismatch -- "
                        f"loss {loss} + expense {expense} = {loss + expense} vs combined {combined} (tol 0.1)"
                    )
        elif c["id"] == "meijiyasuda_nonlife":
            # 2026-09-12: 본편(main PDF)이 owner 제공으로 확보돼 profit 이 extracted 로 바뀜. 두 상태 모두 정합만 검사한다 --
            # not_obtained 면 items 비어야 하고, extracted 면 au 와 같은 손보 검산(경상·순이익 존재, 合算率 항등식)을 적용.
            if profit.get("status") == "not_obtained":
                if profit.get("items"):
                    errors.append(f"{cen}: profit.items expected empty for not_obtained, got {list(profit['items'])}")
            elif profit.get("status") == "extracted":
                for req in ("pl_ordinary_profit", "pl_net_income"):
                    if req not in profit.get("items", {}):
                        errors.append(f"{cen}: profit.items missing required id {req}")
                ratios = profit.get("ratios", {})
                for period in ("cur", "prev"):
                    loss = ratios.get("pl_loss_ratio_pct", {}).get(period)
                    expense = ratios.get("pl_expense_ratio_pct", {}).get(period)
                    combined = ratios.get("pl_combined_ratio_pct", {}).get(period)
                    if None in (loss, expense, combined):
                        errors.append(f"{cen}: profit.ratios[{period}] missing loss/expense/combined for 合算率 check")
                    elif abs((loss + expense) - combined) > 0.1 + 1e-9:
                        errors.append(f"{cen}: profit.ratios[{period}] 合算率 mismatch -- {loss}+{expense} vs {combined}")
            else:
                errors.append(f"{cen}: profit.status unexpected {profit.get('status')!r}")

        # history layer (2026-09-12 ticket 20260912T1440Z)
        _check_history_xref(c, labels, errors)

    return errors


def _check_history_xref(c, labels, errors):
    """history block: label coverage, series/fiscal_years alignment, FY2025/FY2024 == profit cur/prev,
    合算率 identity (shared by esr-posted and esr-not_yet companies). Tolerances carry a 1e-9 epsilon
    because MSI's 5개년표 prints ratios with two decimals (62.85) against one in the 3-year table (62.8)."""
    cen = c["company_en"]
    profit = c.get("profit") or {}
    history = c.get("history") or {}
    years = history.get("fiscal_years", [])
    series = history.get("series", {})
    missing_hist_labels = [k for k in series if k not in labels]
    if missing_hist_labels:
        errors.append(f"{cen}: history ids missing from _meta.labels: {missing_hist_labels}")
    for hid, arr in series.items():
        if len(arr) != len(years):
            errors.append(f"{cen}: history.series[{hid}] length {len(arr)} != fiscal_years length {len(years)}")
    if "FY2025" in years and "FY2024" in years:
        i25, i24 = years.index("FY2025"), years.index("FY2024")
        xref = [("hist_net_premiums_written", "pl_net_premiums_written"), ("hist_net_income", "pl_net_income"),
                ("hist_ordinary_profit", "pl_ordinary_profit"), ("hist_loss_ratio_pct", "pl_loss_ratio_pct"),
                ("hist_expense_ratio_pct", "pl_expense_ratio_pct")]
        pitems = profit.get("items", {})
        for hid, pid in xref:
            harr = series.get(hid)
            pv = pitems.get(pid)
            if not harr or not pv:
                continue
            tol = 0.1 if hid.endswith("_pct") else 1
            if harr[i25] is not None and pv.get("cur") is not None and abs(harr[i25] - pv["cur"]) > tol + 1e-9:
                errors.append(f"{cen}: history.series[{hid}][FY2025] {harr[i25]} != profit.items[{pid}].cur {pv.get('cur')}")
            if harr[i24] is not None and pv.get("prev") is not None and abs(harr[i24] - pv["prev"]) > tol + 1e-9:
                errors.append(f"{cen}: history.series[{hid}][FY2024] {harr[i24]} != profit.items[{pid}].prev {pv.get('prev')}")
    loss, exp, comb = series.get("hist_loss_ratio_pct"), series.get("hist_expense_ratio_pct"), series.get("hist_combined_ratio_pct")
    if loss and exp and comb:
        for i, y in enumerate(years):
            l, e, cv = loss[i], exp[i], comb[i]
            if l is not None and e is not None and cv is not None and abs(cv - (l + e)) > 0.1 + 1e-9:
                errors.append(f"{cen}: history.series 合算率 mismatch at {y} -- loss {l} + expense {e} = {l + e} vs combined {cv} (tol 0.1)")


def main():
    ensure_extracted()
    extracted = load_json(EXTRACTED_PATH)
    schema = load_json(SCHEMA_PATH)
    load_json(RULES_PATH)  # validated readable; rules_ref is a pointer for designer/reader --
                            # its known_deviations are already folded into per-check notes above
    jesr_master = load_json(JESR_MASTER_PATH)
    jesr_esr = load_json(JESR_ESR_PATH)

    out = build(extracted, schema, jesr_master, jesr_esr)
    errors = self_check(out, jesr_esr)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"wrote {OUT_PATH} -- companies={len(out['companies'])}")
    for c in out["companies"]:
        bs = c.get("bs") or {}
        print(f"  {c['id']}: bs status={bs.get('status')} rows={len(bs.get('tree', []))} checks={bs.get('checks')}")
        if c.get("esr_status") == "life_core_only":
            ch = c.get("core_history") or {}
            print(f"  {c['id']}: life_core_only status={ch.get('status')} series={sorted(ch.get('series', {}))}")
            continue
        bl = c.get("by_line") or {}
        print(f"  {c['id']}: by_line items={len(bl.get('items', {}))} checks={bl.get('checks', {}).get('pass')}/{bl.get('checks', {}).get('total')}")
        print(
            f"  {c['id']}: esr_pct={c['headline']['esr_pct']} "
            f"eligible={c['headline']['eligible_capital']} "
            f"required={c['headline']['required_capital']} "
            f"reproduced={c['aggregation']['reproduced']} "
            f"checks={c['aggregation']['checks_pass']}/{c['aggregation']['checks_total']}"
        )
        p = c.get("profit") or {}
        print(
            f"    profit: status={p.get('status')} accounting_basis={p.get('accounting_basis')} "
            f"ifrs17_applied={p.get('ifrs17_applied')} "
            f"pl_ordinary_profit={p.get('items', {}).get('pl_ordinary_profit')} "
            f"pl_net_income={p.get('items', {}).get('pl_net_income')} "
            f"combined_ratio={p.get('ratios', {}).get('pl_combined_ratio_pct')}"
        )
        ctree = c.get("capital_tree") or []
        rtree = c.get("risk_tree") or []
        root_c = ctree[0] if ctree else {}
        root_r = rtree[0] if rtree else {}
        print(
            f"    capital_tree: rows={len(ctree)} root_check={root_c.get('check')}"
        )
        print(
            f"    risk_tree: rows={len(rtree)} root_check={root_r.get('check')}"
        )
        pf = c.get("profit_flow") or {}
        print(
            f"    profit_flow: rows={len(pf.get('rows', []))} missing={pf.get('missing')} "
            f"checks={pf.get('checks')}"
        )

    if errors:
        print("SELF-CHECK FAILED:")
        for e in errors:
            print(" -", e)
        return 1
    print("SELF-CHECK OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
