"""Assemble jp/jesr_detail.json -- per-company ESR detail pages for jp/company.html.

Publishing-stage builder (stdlib only). Contract is fixed with designer -- do not
rename keys. See inbox/publishing/20260912T1120Z__owner__JP_MULTI__jesr_detail_json.md
for the full contract and inputs.

Inputs:
  J-ESR/raw/fy2025_samples/extracted_sample_values.json  (per-item extraction + checks;
      generated by J-ESR/extract_esr_template_samples.py -- run automatically if missing)
  J-ESR/esr_disclosure_schema.json                        (item id -> labels/unit/kics_item_ref)
  J-ESR/esr_aggregation_rules.json                        (rules_ref pointer only; the
      known_deviations it documents are already reflected in the per-check "note" fields
      inside extracted_sample_values.json, so nothing further is merged from it here)
  jp/jesr_esr.json                                        (published headline + source
      metadata for company records; used for the self-check cross-reference)
  J-ESR/jesr_master.json                                  (pre-exclusion master -- the
      published jp/jesr_esr.json intentionally drops source_url/doc_type/doc_date/
      preliminary for excluded subsidiaries such as meijiyasuda_nonlife, so those four
      fields are looked up here instead of being left blank)

Only companies with census.status == "posted" in extracted_sample_values.json are
included (currently 2: au_nonlife, meijiyasuda_nonlife -- nnlife is ESR-not-yet-disclosed
and is excluded).

Each included company also gets a "profit" block (layer:"profit" in the schema, added
2026-09-12 per inbox/publishing/20260912T1240Z__owner__JP_MULTI__jesr_detail_profit_block.md).
"items" holds every non-null profit:pl/uw/inv id for that company; "ratios" (nonlife
loss/expense/combined ratio) and "core" (life 基礎利益 decomposition + 三利源) are
convenience sub-views that duplicate a subset of the same ids -- same "items" + narrower
view pattern already used above for capital/risk/market_sub. meijiyasuda_nonlife has no
profit tables in its excerpt volume (main volume blocked, see extract_esr_template_samples.py)
so its profit.status is "not_obtained" and items/ratios/core are all empty.

Output: jp/jesr_detail.json (UTF-8, no BOM, ensure_ascii=False).
Self-check runs after the file is written; on failure the script exits 1 (file is still
written so a human can inspect it, but the caller must not treat exit 1 as success).
"""
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

JESR_DIR = Path(__file__).resolve().parent
ROOT = JESR_DIR.parent
JP_DIR = ROOT / "jp"

EXTRACTOR_SCRIPT = JESR_DIR / "extract_esr_template_samples.py"
EXTRACTED_PATH = JESR_DIR / "raw" / "fy2025_samples" / "extracted_sample_values.json"
SCHEMA_PATH = JESR_DIR / "esr_disclosure_schema.json"
RULES_PATH = JESR_DIR / "esr_aggregation_rules.json"
JESR_MASTER_PATH = JESR_DIR / "jesr_master.json"
JESR_ESR_PATH = JP_DIR / "jesr_esr.json"
OUT_PATH = JP_DIR / "jesr_detail.json"

RISK_KEYS = [
    ("rc_life", "rc_life"),
    ("rc_nonlife", "rc_nonlife"),
    ("rc_catastrophe", "rc_catastrophe"),
    ("rc_market", "rc_market"),
    ("rc_credit", "rc_credit"),
    ("rc_operational", "rc_operational"),
    ("diversification_effect", "rc_diversification"),
    ("rc_pre_tax", "rc_pre_tax"),
    ("tax_effect", "rc_tax_effect"),
    ("rc_post_tax", "rc_post_tax"),
]
MARKET_SUB_KEYS = [
    "rc_mkt_interest", "rc_mkt_spread", "rc_mkt_equity",
    "rc_mkt_property", "rc_mkt_fx", "rc_mkt_concentration",
]

# profit layer (2026-09-12): id groupings by schema `table` tag.
PROFIT_META_TABLE = "profit:meta"
PROFIT_RATIO_TABLE = "profit:ratio"           # nonlife 損害率/事業費率/合算率
PROFIT_CORE_TABLES = {"profit:core", "profit:three"}  # life 基礎利益 decomposition + 三利源


def ensure_extracted():
    if EXTRACTED_PATH.exists():
        return
    print(f"[build_jesr_detail_json] {EXTRACTED_PATH} missing -- running extractor first")
    result = subprocess.run([sys.executable, str(EXTRACTOR_SCRIPT)], cwd=str(ROOT))
    if not EXTRACTED_PATH.exists():
        raise SystemExit(
            f"extractor exited {result.returncode} and still did not produce {EXTRACTED_PATH}"
        )


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def r1(x):
    return round(x, 1) if isinstance(x, (int, float)) else x


def build_profit_block(profit_raw, items_by_id):
    """Assemble the profit block for one company from its extracted profit.values/meta.

    items_by_id: schema id -> schema item dict (for the `table` tag lookup).
    """
    values = profit_raw.get("values") or {}
    meta = profit_raw.get("meta") or {}
    source_doc = meta.get("profit_source_doc")
    status = "not_obtained" if isinstance(source_doc, str) and source_doc.startswith("NOT_ACQUIRED") else "extracted"

    items = {}
    ratios = {}
    core = {}
    for pid, val in values.items():
        it = items_by_id.get(pid)
        if it is None or it.get("table") == PROFIT_META_TABLE:
            continue  # accounting_basis/ifrs17_applied/evidence/source_doc are top-level fields, not items
        if not isinstance(val, dict):
            continue
        cur = val.get("cur")
        prev = val.get("prev")
        if cur is None and prev is None:
            continue  # non-null 만 (2026-09-12 ticket)
        entry = {"cur": cur, "prev": prev}
        items[pid] = entry
        table = it.get("table")
        if table == PROFIT_RATIO_TABLE:
            ratios[pid] = entry
        elif table in PROFIT_CORE_TABLES:
            core[pid] = entry

    return {
        "accounting_basis": meta.get("accounting_basis"),
        "ifrs17_applied": meta.get("ifrs17_applied"),
        "evidence": meta.get("accounting_basis_evidence"),
        "source_doc": source_doc,
        "unit": "JPY_million",
        "items": items,
        "ratios": ratios,
        "core": core,
        "status": status,
    }


def build(extracted, schema, jesr_master, jesr_esr):
    labels = {}
    items_by_id = {}
    for it in schema["items"]:
        items_by_id[it["id"]] = it
        ja = it["labels_ja"][0] if it.get("labels_ja") else None
        labels[it["id"]] = {
            "ja": ja,
            "ko": it.get("ko"),
            "unit": it.get("unit"),
            "kics_item_ref": it.get("kics_item_ref"),
            "pl_item_ref": it.get("pl_item_ref"),
        }

    master_by_en = {r["company_en"]: r for r in jesr_master.get("records", [])}
    public_by_en = {r["company_en"]: r for r in jesr_esr.get("records", [])}
    for r in jesr_esr.get("_meta", {}).get("excluded_subsidiaries", []):
        public_by_en.setdefault(r["company_en"], r)

    companies_out = []
    for cid, comp in extracted["companies"].items():
        if comp.get("census", {}).get("status") != "posted":
            continue
        esr = comp["esr"]
        values = esr["values"]
        method = esr["method"]
        merged = {**values, **method}
        summ = extracted["summary"][cid]

        company_en = comp["company_en"]
        src = master_by_en.get(company_en, {})

        headline = {
            "eligible_capital": values.get("eligible_capital"),
            "required_capital": values.get("required_capital"),
            "esr_pct": values.get("esr_pct"),
            "preliminary": src.get("preliminary"),
        }

        capital = {
            it["id"]: merged.get(it["id"])
            for it in schema["items"]
            if it["table"] == "T2" and merged.get(it["id"]) is not None
        }

        risk = {out_key: merged.get(src_key) for out_key, src_key in RISK_KEYS}
        market_sub = {k: merged.get(k) for k in MARKET_SUB_KEYS}

        sensitivity = []
        sens = esr.get("sensitivity") or {}
        levels = sens.get("levels", {}).get("esr_pct", {})
        diffs = sens.get("diffs", {}).get("esr_pct", {})
        for scen in sens.get("scenarios", []):
            if scen == "base":
                continue
            lvl = levels.get(scen)
            dpp = diffs.get(scen)
            if lvl is None or dpp is None:
                continue  # omitted/undisclosed scenario -- leave out rather than guess
            sid = f"sens_{scen}_esr_pct"
            sitem = items_by_id.get(sid)
            sensitivity.append({
                "id": sid,
                "label_ja": sitem["labels_ja"][0] if sitem else scen,
                "esr_pct": r1(lvl),
                "delta_pp": r1(dpp),
            })

        deviations = []
        for chk in esr.get("checks", []):
            if chk["id"] in summ.get("checks_info_failed", []):
                deviations.append({
                    "id": chk["id"],
                    "lhs": chk.get("lhs"),
                    "rhs": chk.get("rhs"),
                    "note": chk.get("note", ""),
                })

        agg_recompute = esr.get("aggregation_recompute") or {}
        aggregation = {
            "top_sqrt": agg_recompute.get("top_sqrt"),
            "simple_sum": agg_recompute.get("simple_sum_ABCDE"),
            "reproduced": len(summ.get("checks_failed", [])) == 0,
            "checks_pass": summ.get("checks_pass"),
            "checks_total": summ.get("checks_total"),
            "deviations": deviations,
        }

        axes_values = comp.get("axes", {}).get("values", {})
        axes = {k: v for k, v in axes_values.items() if v is not None}

        items = {
            it["id"]: merged.get(it["id"])
            for it in schema["items"]
            if it["layer"] == "esr" and merged.get(it["id"]) is not None
        }

        profit = build_profit_block(comp.get("profit") or {}, items_by_id)

        companies_out.append({
            "id": cid,
            "company_jp": comp.get("company_jp"),
            "company_en": company_en,
            "sector": comp.get("sector"),
            "scope": comp.get("scope"),
            "as_of": comp.get("as_of"),
            "source_url": src.get("source_url"),
            "doc_type": src.get("doc_type"),
            "doc_date": src.get("doc_date"),
            "headline": headline,
            "capital": capital,
            "risk": risk,
            "market_sub": market_sub,
            "sensitivity": sensitivity,
            "aggregation": aggregation,
            "axes": axes,
            "items": items,
            "profit": profit,
        })

    meta_src = jesr_esr.get("_meta", {})
    return {
        "_meta": {
            "as_of": meta_src.get("as_of"),
            "as_of_label_ja": meta_src.get("as_of_label_ja"),
            "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "unit": "JPY_million",
            "schema_ref": "J-ESR/esr_disclosure_schema.json",
            "rules_ref": "J-ESR/esr_aggregation_rules.json",
            "labels": labels,
            "next_update": meta_src.get("next_update"),
            "coverage": {
                "detail_posted": len(companies_out),
                "posted_total": len(jesr_esr.get("records", [])),
                "census_total": meta_src.get("census", {}).get("total"),
            },
        },
        "companies": companies_out,
    }


def self_check(out, jesr_esr):
    errors = []
    companies = out["companies"]
    if len(companies) != 2:
        errors.append(f"expected exactly 2 companies, got {len(companies)}")

    public_by_en = {r["company_en"]: r for r in jesr_esr.get("records", [])}
    for r in jesr_esr.get("_meta", {}).get("excluded_subsidiaries", []):
        public_by_en.setdefault(r["company_en"], r)

    labels = out["_meta"]["labels"]

    for c in companies:
        cen = c["company_en"]
        pub = public_by_en.get(cen)
        if pub is None:
            errors.append(f"{cen}: not found in jp/jesr_esr.json records/excluded_subsidiaries")
        elif c["headline"]["esr_pct"] != pub.get("esr_pct"):
            errors.append(
                f"{cen}: headline.esr_pct {c['headline']['esr_pct']} != "
                f"jp/jesr_esr.json {pub.get('esr_pct')}"
            )
        if c["risk"]["rc_post_tax"] != c["headline"]["required_capital"]:
            errors.append(
                f"{cen}: risk.rc_post_tax {c['risk']['rc_post_tax']} != "
                f"headline.required_capital {c['headline']['required_capital']}"
            )
        missing_labels = [k for k in c["items"].keys() if k not in labels]
        if missing_labels:
            errors.append(f"{cen}: items ids missing from _meta.labels: {missing_labels}")
        # unit passthrough guard: no JPY_million -> JPY_100million (or any other) conversion
        # may have been applied anywhere in this builder.
        if c["items"].get("eligible_capital") != c["headline"]["eligible_capital"]:
            errors.append(
                f"{cen}: unit/passthrough mismatch -- items.eligible_capital "
                f"{c['items'].get('eligible_capital')} != headline.eligible_capital "
                f"{c['headline']['eligible_capital']}"
            )

        # profit layer (2026-09-12 ticket)
        profit = c.get("profit") or {}
        missing_profit_labels = [
            k for k in list(profit.get("items", {})) + list(profit.get("ratios", {})) + list(profit.get("core", {}))
            if k not in labels
        ]
        if missing_profit_labels:
            errors.append(f"{cen}: profit ids missing from _meta.labels: {missing_profit_labels}")

        if c["id"] == "au_nonlife":
            if profit.get("status") != "extracted":
                errors.append(f"{cen}: profit.status expected 'extracted', got {profit.get('status')!r}")
            for req in ("pl_ordinary_profit", "pl_net_income"):
                if req not in profit.get("items", {}):
                    errors.append(f"{cen}: profit.items missing required id {req}")
            ratios = profit.get("ratios", {})
            for period in ("cur", "prev"):
                loss = ratios.get("pl_loss_ratio_pct", {}).get(period)
                expense = ratios.get("pl_expense_ratio_pct", {}).get(period)
                combined = ratios.get("pl_combined_ratio_pct", {}).get(period)
                if None in (loss, expense, combined):
                    errors.append(f"{cen}: profit.ratios[{period}] missing loss/expense/combined for 合算率 check")
                elif abs((loss + expense) - combined) > 0.1 + 1e-9:
                    errors.append(
                        f"{cen}: profit.ratios[{period}] 合算率 mismatch -- "
                        f"loss {loss} + expense {expense} = {loss + expense} vs combined {combined} (tol 0.1)"
                    )
        elif c["id"] == "meijiyasuda_nonlife":
            # 2026-09-12: 본편(main PDF)이 owner 제공으로 확보돼 profit 이 extracted 로 바뀜. 두 상태 모두 정합만 검사한다 --
            # not_obtained 면 items 비어야 하고, extracted 면 au 와 같은 손보 검산(경상·순이익 존재, 合算率 항등식)을 적용.
            if profit.get("status") == "not_obtained":
                if profit.get("items"):
                    errors.append(f"{cen}: profit.items expected empty for not_obtained, got {list(profit['items'])}")
            elif profit.get("status") == "extracted":
                for req in ("pl_ordinary_profit", "pl_net_income"):
                    if req not in profit.get("items", {}):
                        errors.append(f"{cen}: profit.items missing required id {req}")
                ratios = profit.get("ratios", {})
                for period in ("cur", "prev"):
                    loss = ratios.get("pl_loss_ratio_pct", {}).get(period)
                    expense = ratios.get("pl_expense_ratio_pct", {}).get(period)
                    combined = ratios.get("pl_combined_ratio_pct", {}).get(period)
                    if None in (loss, expense, combined):
                        errors.append(f"{cen}: profit.ratios[{period}] missing loss/expense/combined for 合算率 check")
                    elif abs((loss + expense) - combined) > 0.1 + 1e-9:
                        errors.append(f"{cen}: profit.ratios[{period}] 合算率 mismatch -- {loss}+{expense} vs {combined}")
            else:
                errors.append(f"{cen}: profit.status unexpected {profit.get('status')!r}")

    return errors


def main():
    ensure_extracted()
    extracted = load_json(EXTRACTED_PATH)
    schema = load_json(SCHEMA_PATH)
    load_json(RULES_PATH)  # validated readable; rules_ref is a pointer for designer/reader --
                            # its known_deviations are already folded into per-check notes above
    jesr_master = load_json(JESR_MASTER_PATH)
    jesr_esr = load_json(JESR_ESR_PATH)

    out = build(extracted, schema, jesr_master, jesr_esr)
    errors = self_check(out, jesr_esr)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"wrote {OUT_PATH} -- companies={len(out['companies'])}")
    for c in out["companies"]:
        print(
            f"  {c['id']}: esr_pct={c['headline']['esr_pct']} "
            f"eligible={c['headline']['eligible_capital']} "
            f"required={c['headline']['required_capital']} "
            f"reproduced={c['aggregation']['reproduced']} "
            f"checks={c['aggregation']['checks_pass']}/{c['aggregation']['checks_total']}"
        )
        p = c.get("profit") or {}
        print(
            f"    profit: status={p.get('status')} accounting_basis={p.get('accounting_basis')} "
            f"ifrs17_applied={p.get('ifrs17_applied')} "
            f"pl_ordinary_profit={p.get('items', {}).get('pl_ordinary_profit')} "
            f"pl_net_income={p.get('items', {}).get('pl_net_income')} "
            f"combined_ratio={p.get('ratios', {}).get('pl_combined_ratio_pct')}"
        )

    if errors:
        print("SELF-CHECK FAILED:")
        for e in errors:
            print(" -", e)
        return 1
    print("SELF-CHECK OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
