# -*- coding: utf-8 -*-
"""CSM waterfall 3-color status matrix (company x quarter):
  G = gold-validated (a hand-built CSM gold sheet covers this cell and it passes)
  c = continuity-OK  (no gold; within-year 기초 constant under YTD, value plausible)
  ~ = wobble         (no gold; within-year 기초 varies >2% — likely 별도/연결 or restatement)
  ? = suspect        (no gold; garbage: |기초| < 25% of company median, or wrong sign)
  . = none           (no CSM detected — PAA-only / not disclosed; blank cell)
Writes docs/csm_status_matrix.md. Keeper."""
from __future__ import annotations
import glob
import json
from collections import defaultdict
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
master = json.loads((ROOT / "data/dart/viz/csm_waterfall_master_diag.json").read_text(encoding="utf-8"))

opening = {}            # (code, q) -> 기초(억)
names, sb = {}, {}
for r in master:
    if r["항목번호"] == 1:
        opening[(r["원보험사코드"], r["공시분기"])] = r["값"]
    names[r["원보험사코드"]] = r["원수사명"]
    sb[r["원보험사코드"]] = r["생손보여부"]

QS = [f"{y}.{q}Q" for y in (2023, 2024, 2025, 2026) for q in (1, 2, 3, 4)]
QS = [q for q in QS if q != "2026.2Q"][:13]

# --- gold-validated cells: read the gold sheets, check 기초 matches master within 1% ---
ALIAS = {"롯데손보": "KR0003", "DB손보": "KR0011", "농협생명": "KR0104", "동양생명": "KR0087",
         "삼성생명": "KR0069", "교보생명": "KR0073", "미래에셋생명": "KR0079", "푸본현대생명": "KR0083",
         "신한라이프": "KR0094", "신한라이프생명보험": "KR0094"}
FILE_OVERRIDE = {"CSM waterfall_교보생명.xlsx": ("KR0073", "2025.4Q")}
NAME2CODE = {r["원수사명"]: r["원보험사코드"] for r in master}

gold_pass = set()
for f in glob.glob(str(ROOT / "CSM waterfall_*.xlsx")):
    wb = openpyxl.load_workbook(f, data_only=True)
    ws = wb["Sheet2"] if "Sheet2" in wb.sheetnames else wb[wb.sheetnames[0]]
    g, code, name, q = {}, None, None, None
    for row in list(ws.iter_rows(values_only=True))[1:]:
        if row[4] is None:
            continue
        seg = [c for c in row[7:] if isinstance(c, (int, float))]
        g[int(row[4])] = sum(seg) if seg else None
        code = code or row[0]
        name = name or row[1]
        q = q or row[6]
    ov = FILE_OVERRIDE.get(Path(f).name)
    if ov:
        code, q = ov
    elif not (code and str(code).startswith("KR")):
        code = ALIAS.get(name) or NAME2CODE.get(name)
    gv = None if g.get(1) is None else g[1] / 100.0
    cv = opening.get((code, q))
    if gv is not None and cv is not None and abs(gv - cv) <= max(1.0, abs(gv) * 0.01):
        gold_pass.add((code, q))

# --- per-company continuity classification per cell ---
def cell_mark(code, q):
    if (code, q) in gold_pass:
        return "G"
    v = opening.get((code, q))
    if v is None:
        return "."
    series = {qq: opening.get((code, qq)) for qq in QS if (code, qq) in opening}
    vals = [x for x in series.values() if x is not None]
    med = sorted(vals)[len(vals) // 2] if vals else 0.0
    if abs(med) > 1000 and (abs(v) < 0.25 * abs(med) or (v < 0 < med)):
        return "?"
    yr = [series.get(f"{q[:4]}.{i}Q") for i in (1, 2, 3, 4)]
    yr = [x for x in yr if x is not None]
    if len(yr) >= 2 and max(abs(x) for x in yr) > 1:
        dev = (max(yr) - min(yr)) / max(abs(max(yr)), abs(min(yr)), 1)
        if dev > 0.02:
            return "~"
    return "c"

codes = sorted(names, key=lambda k: (sb.get(k, ""), names[k]))
L = ["# CSM Waterfall — 3-color status matrix (company × quarter)", "",
     "Generated by `scripts/_csm_status_matrix.py` from `csm_waterfall_master_diag.json`",
     "+ the hand-built `CSM waterfall_*.xlsx` gold sheets.", "",
     "- **G** = gold-validated (gold sheet covers this cell, 기초 matches ≤1%)",
     "- **c** = continuity-OK (no gold; within-year 기초 constant under YTD, plausible)",
     "- **~** = wobble (no gold; within-year 기초 varies >2% — 별도/연결 or restatement)",
     "- **?** = suspect (no gold; garbage: |기초| < 25% of company median or wrong sign)",
     "- **.** = none (no CSM — PAA-only / not disclosed)", "",
     "| Company (생손보) | " + " | ".join(q[2:] for q in QS) + " |",
     "|" + "---|" * (len(QS) + 1)]
counts = defaultdict(int)
for code in codes:
    row = []
    for q in QS:
        m = cell_mark(code, q) if (code, q) in opening or (code, q) in gold_pass else "."
        row.append(m)
        if m != ".":
            counts[m] += 1
    L.append(f"| {names[code]} ({sb.get(code,'')[:2]}) | " + " | ".join(row) + " |")
L += ["", "## Tally",
      f"- **G (gold)**: {counts['G']}   **c (continuity)**: {counts['c']}   "
      f"**~ (wobble)**: {counts['~']}   **? (suspect)**: {counts['?']}",
      "",
      "Suspect (?) and wobble (~) cells without gold are where additional answer sheets",
      "would tighten validation; PAA-only insurers correctly show blank (no CSM)."]

(ROOT / "docs" / "csm_status_matrix.md").write_text("\n".join(L), encoding="utf-8")
print("wrote docs/csm_status_matrix.md")
print(f"G={counts['G']} c={counts['c']} ~={counts['~']} ?={counts['?']}")
print("suspect cells:", [f"{names[c]} {q}" for c in codes for q in QS if cell_mark(c, q) == "?"])
print("wobble cells:", [f"{names[c]} {q}" for c in codes for q in QS if cell_mark(c, q) == "~"][:40])
