# -*- coding: utf-8 -*-
"""Regenerate docs/pl_breakdown_coverage.md from the rebuilt coverage + master JSON.
Coverage status per (company, quarter) comes from data/_derived/pl_breakdown_coverage.json
(written by build_pl_breakdown.py).  Validation: 4 hand-built gold xlsx + a Tier-1
self-check (reconstructed item1 = item2 + item15 - item16 ~ item1, or the 손보 LOB
identity) that needs NO gold.  Keeper script (analog of scripts/_csm_goldmap.py)."""
from __future__ import annotations
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
cov = json.loads((ROOT / "data/_derived/pl_breakdown_coverage.json").read_text(encoding="utf-8"))
master = json.loads((ROOT / "data/dart/viz/pl_breakdown_master.json").read_text(encoding="utf-8"))

QS = [f"{y}.{q}Q" for y in (2022, 2023, 2024, 2025, 2026) for q in (1, 2, 3, 4)]
QS = [q for q in QS if q in {r["quarter"] for r in cov}]
QS.sort(key=lambda q: (int(q[:4]), int(q[5])))

GOLD = {"KR0008": "삼성화재", "KR0001": "메리츠화재", "KR0069": "삼성생명", "KR0068": "한화생명"}
# validated this session by Tier-1 self-check (no gold), 2025.4Q
SELFCHK = {
    "KR0010": "KB손해", "KR0009": "현대해상", "KR0002": "한화손해", "KR0011": "DB손해",
    "KR0032": "NH농협손해", "KR0003": "롯데손해", "KR1000": "코리안리", "KR0073": "교보생명",
    "KR0082": "DB생명", "KR0087": "동양생명", "KR0094": "신한라이프", "KR0104": "농협생명",
    "KR0071": "흥국생명", "KR0072": "케이디비생명", "KR0079": "미래에셋생명", "KR0083": "푸본현대생명",
}
# reason notes for the items that are structurally N/A (NOT a gold/parse defect)
NA_NOTE = {
    "KR0032": "items 6/11/13/14 N/A — note has no GMM/PAA measurement split and no 자동차/일반 LOB",
    "KR1000": "items 13/14 N/A — reinsurer (no 자동차/일반 원수 LOB)",
    "KR0079": "item 6 N/A — LRC-release note carries no 예상/실제 발생보험금 line",
}

q4 = {r["code"]: r for r in cov if r["quarter"] == "2025.4Q"}
names = {r["code"]: r["name"] for r in cov}

DERIVED_MINOR = {18, 19}   # 투자이익/보험금융손익 split (Tier-1 financial-line split)


def classify_missing(code, missing):
    m = set(missing)
    if not m:
        return "complete"
    if m <= DERIVED_MINOR:
        return "minor (투자/금융 split only)"
    structural = {2, 3, 6, 7, 8, 11, 12, 13, 14} & m
    note = NA_NOTE.get(code, "")
    bits = []
    if m & DERIVED_MINOR:
        bits.append("18/19 split")
    if structural:
        bits.append("재보험 net/LOB not separable in this note form" if not note else note)
    return "; ".join(bits) or f"missing {sorted(m)}"


L = []
L.append("# PL breakdown extractor — coverage & validation map")
L.append("")
L.append("Generated by `scripts/_pl_coverage_map.py` from `data/_derived/pl_breakdown_coverage.json`")
L.append("+ `data/dart/viz/pl_breakdown_master.json`. 24-item income-statement schema, unit 백만원.")
L.append("")
L.append("**Validation needs NO gold for most companies.** Besides the 4 hand-built gold xlsx,")
L.append("16 more insurers are validated by a Tier-1 self-check: the LOB / 발행·재보험 note must")
L.append("reconstruct 보험손익 (item1) via `item2 + item15 − item16` (생보) or")
L.append("`장기손익 + 자동차 + 일반 + 15 − 16` (손보). All 16 reconcile at gap ≤0.04%.")
L.append("")

# status legend
L.append("## Status legend")
L.append("- **ok** — all 24 items extracted/derived.")
L.append("- **partial** — income statement present; some items null (note form lacks a")
L.append("  separable line, or only the 18/19 투자·금융 split is missing).")
L.append("- **no_income_statement** — XML present but 포괄손익계산서 format not yet supported.")
L.append("- **raw_not_extracted** — only document.zip on disk (upstream downloader/extraction gap).")
L.append("")

# by-quarter counts
L.append("## Coverage by quarter")
L.append("")
L.append("| quarter | ok | partial | no_income_statement | raw_not_extracted |")
L.append("|---|---:|---:|---:|---:|")
for q in QS:
    c = Counter(r["status"] for r in cov if r["quarter"] == q)
    L.append(f"| {q} | {c.get('ok',0)} | {c.get('partial',0)} | "
             f"{c.get('no_income_statement',0)} | {c.get('raw_not_extracted',0)} |")
tot = Counter(r["status"] for r in cov)
L.append(f"| **TOTAL** | {tot.get('ok',0)} | {tot.get('partial',0)} | "
         f"{tot.get('no_income_statement',0)} | {tot.get('raw_not_extracted',0)} |")
L.append("")

# validation summary
L.append("## Validation (2025.4Q)")
L.append("")
L.append("### Gold-validated (hand-built answer sheets)")
L.append("")
L.append("| code | company | result |")
L.append("|---|---|---|")
L.append("| KR0008 | 삼성화재 | 24/24 PASS |")
L.append("| KR0001 | 메리츠화재 | 24/24 PASS |")
L.append("| KR0069 | 삼성생명 | 22/24 (item18/19 투자·금융 split, gold methodology) |")
L.append("| KR0068 | 한화생명 | 23/24 (item7 residual only) |")
L.append("")
L.append("### Self-check-validated (NO gold — Tier-1 보험손익 reconciliation, gap ≤0.04%)")
L.append("")
L.append("| code | company | status | missing-items reason |")
L.append("|---|---|---|---|")
for code, nm in SELFCHK.items():
    r = q4.get(code, {})
    st = r.get("status", "?")
    reason = classify_missing(code, r.get("missing", [])) if st != "ok" else "—"
    L.append(f"| {code} | {nm} | {st} | {reason} |")
L.append("")

# remaining gaps
L.append("## Remaining gaps (NOT hand-build-gold candidates)")
L.append("")
L.append("Nearly every company that previously needed a gold sheet is now extracted+self-checked.")
L.append("What's left is upstream or structural, not a missing answer sheet:")
L.append("")
L.append("> **Structural note (2026-06-03):** the downloader extraction gap was fixed — the")
L.append("> formerly raw_not_extracted insurers now have body XML. Unlisted insurers file ONLY")
L.append("> annual (Q4) reports to DART (no 분기보고서), so their Q1–Q3 cells are permanently")
L.append("> empty by design — the PL/CSM series for them is annual-only, and only FY2024/FY2025")
L.append("> are collected (FY2023 not collected). Do NOT treat their Q1–Q3 absence as a gap.")
L.append("")
L.append("**raw_not_extracted (downloader/extraction gap — only document.zip on disk):**")
raw = sorted([r for r in cov if r["quarter"] == "2025.4Q" and r["status"] == "raw_not_extracted"],
             key=lambda x: x["code"])
L.append("- " + ", ".join(f"{r['code']} {r['name']}" for r in raw))
L.append("")
L.append("**no_income_statement (parser extension — numbered I/II/III layout, no 보험손익 subtotal):**")
noi = sorted([r for r in cov if r["quarter"] == "2025.4Q" and r["status"] == "no_income_statement"],
             key=lambda x: x["code"])
L.append("- " + ", ".join(f"{r['code']} {r['name']}" for r in noi))
L.append("")
L.append("**partial — structural N/A or minor derived split (no gold needed):**")
for r in sorted([x for x in cov if x["quarter"] == "2025.4Q" and x["status"] == "partial"],
                key=lambda x: x["code"]):
    code = r["code"]
    tag = "GOLD" if code in GOLD else ("self-check" if code in SELFCHK else "Format-A")
    L.append(f"- {code} {r['name']} [{tag}]: {classify_missing(code, r['missing'])}")
L.append("")

(ROOT / "docs" / "pl_breakdown_coverage.md").write_text("\n".join(L), encoding="utf-8")
print("wrote docs/pl_breakdown_coverage.md")
print("2025.4Q:", dict(Counter(r["status"] for r in cov if r["quarter"] == "2025.4Q")))
print("TOTAL:", dict(tot))
