# -*- coding: utf-8 -*-
"""PL no-gold self-check across ALL company-quarters.

For every (company, quarter) in pl_breakdown_master.json, run gold-free checks and emit a
per-cell status + coverage-by-quarter table to docs/pl_selfcheck_matrix.md.

What is (and isn't) a universal invariant
-----------------------------------------
After inspecting the 4 gold sheets AND the wider universe, only TWO income-statement
identities are universal:
    22 (세전이익)  == 20 (영업이익) + 21 (영업외손익)
    24 (당기순이익) == 22 (세전이익) - 23 (법인세)          [enforced in assemble via FIX B]
The tempting `20 == 1 (보험손익) + 17 (투자손익)` is NOT universal: insurers with a
'기타 영업이익(비용)' block (현대해상) or a 기타사업비용-gross 투자손익 line (교보/미래에셋/KDB)
have 영업이익 ≠ 보험손익 + 투자손익 by presentation, yet items 1/20/24 are individually
correct (verified against owner gold-hints).  So 20=1+17 is reported as an informational
'structure' note, never as 'broken'.

Tier-2 cross-check (RC): when item2 (생명장기손익 / 장기손익) is present we reconcile it to
the statement's 보험손익:  생보  item1 ~ item2 + item15 - item16
                           손보  item1 ~ item2 + item13 + item14 + item15 - item16
This is the meaningful Tier-2 quality signal (a mis-extracted breakdown fails RC).

(Within-year YTD continuity was dropped: cumulative PROFIT is not monotone — a loss quarter
can shrink cumulative 당기순이익 — so a magnitude-monotonic test produced false wobble.)

Cell status:
  G  gold-validated (4 PL gold sheets, 2025.4Q)
  x  broken — statement does not close (22 != 20+21)
  ~  wobble — Tier-2 present but does not reconcile (RC fails)
  v  verified — Tier-2 present and reconciles (RC holds)
  i  ID-only — statement closes; no Tier-2 to cross-check
  .  none — no income statement
Keeper diagnostic; only writes the .md."""
from __future__ import annotations
import json
from collections import defaultdict, Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
master = json.loads((ROOT / "data/dart/viz/pl_breakdown_master.json").read_text(encoding="utf-8"))

cell = defaultdict(dict)
names, sb = {}, {}
for r in master:
    cell[(r["원보험사코드"], r["공시분기"])][r["항목번호"]] = r["값"]
    names[r["원보험사코드"]] = r["원수사명"]
    sb[r["원보험사코드"]] = r["생손보여부"]

GOLD = {("KR0008", "2025.4Q"), ("KR0001", "2025.4Q"),
        ("KR0069", "2025.4Q"), ("KR0068", "2025.4Q")}

QS = [f"{y}.{q}Q" for y in (2023, 2024, 2025, 2026) for q in (1, 2, 3, 4)]
QS = [q for q in QS if any((c, q) in cell for c in names)]


def rel_ok(a, b, tol=0.01, floor=1.0):
    if a is None or b is None:
        return None
    return abs(a - b) <= max(floor, abs(b) * tol)


def close_stmt(v):
    """Universal statement-closure: 22 == 20 + 21. None if not testable."""
    if None in (v.get(20), v.get(21), v.get(22)):
        return None
    return rel_ok(v[22], v[20] + v[21], tol=0.012, floor=2.0)


def struct_note(v):
    """Informational: does 20 == 1 + 17 hold?  False => insurer has 기타영업 structure."""
    if None in (v.get(1), v.get(17), v.get(20)):
        return None
    return rel_ok(v[20], v[1] + v[17], tol=0.012, floor=2.0)


def check_rc(v, is_life):
    """Tier-2 → 보험손익 reconciliation, convention-agnostic.

    Whether 기타사업비용 (item16) sits INSIDE 보험손익 or is reported separately varies by
    insurer, so accept EITHER:  item1 ≈ Σ(LOB)            (16 already in the LOB breakdown)
                            or  item1 ≈ Σ(LOB) + 15 − 16  (16 separate).
    Σ(LOB) = item2 (+ item13 + item14 for 손보).  A gross Tier-2 mis-extraction (unit error,
    wrong table) fails both; a mere convention difference passes one."""
    if v.get(2) is None or v.get(1) is None:
        return None
    lob = (v[2] or 0) + (0 if is_life else (v.get(13) or 0) + (v.get(14) or 0))
    bare = rel_ok(v[1], lob, tol=0.02, floor=2.0)
    adj = rel_ok(v[1], lob + (v.get(15) or 0) - (v.get(16) or 0), tol=0.02, floor=2.0)
    return bool(bare or adj)


def cell_status(code, q):
    if (code, q) in GOLD:
        return "G"
    if (code, q) not in cell:
        return "."
    v = cell[(code, q)]
    if v.get(1) is None and v.get(24) is None:
        return "."
    if close_stmt(v) is False:
        return "x"
    rc = check_rc(v, sb.get(code) == "생명보험")
    if rc is False:
        return "~"
    if rc is True:
        return "v"
    return "i"


codes = sorted(names, key=lambda k: (sb.get(k, ""), names[k]))
L = ["# PL breakdown — no-gold self-check matrix (company × quarter)", "",
     "Generated by `scripts/_pl_selfcheck.py` from `pl_breakdown_master.json`.", "",
     "> **Read this first:** v/i/~ ALL have a healthy Tier-1 income statement (FS-API).  The",
     "> letter only grades the **Tier-2 decomposition** (footnote: 장기/자동차/일반 + CSM상각).",
     "> Only **x** is a Tier-1 problem.", "",
     "- **G** gold-validated (PL gold sheets)",
     "- **v** Tier-1 OK + Tier-2 decomposition present & reconciles to 보험손익",
     "- **i** Tier-1 OK + Tier-2 decomposition NOT extracted (footnote not in FS API → hand-parse pending)",
     "- **~** Tier-1 OK + Tier-2 present but does not reconcile (RC fails)",
     "- **x** Tier-1 BROKEN: income statement does not close (22 ≠ 20+21) — HTML-fallback cell",
     "- **.** none: no income statement at all", "",
     "| Company (생손보) | " + " | ".join(q[2:] for q in QS) + " |",
     "|" + "---|" * (len(QS) + 1)]
counts = Counter()
broken, wobble, struct = [], [], []
for code in codes:
    row = []
    for q in QS:
        m = cell_status(code, q)
        row.append(m)
        counts[m] += 1
        if m == "x":
            broken.append(f"{names[code]} {q}")
        elif m == "~":
            wobble.append(f"{names[code]} {q}")
        if (code, q) in cell and struct_note(cell[(code, q)]) is False and m not in (".", "x"):
            struct.append(f"{names[code]} {q}")
    L.append(f"| {names[code]} ({(sb.get(code) or '')[:2]}) | " + " | ".join(row) + " |")

_stmt = counts['G'] + counts['v'] + counts['i'] + counts['~']   # cells with a statement
L += ["", "## Tally",
      f"- **G**:{counts['G']}  **v**:{counts['v']}  **i**:{counts['i']}  "
      f"**~**:{counts['~']}  **x**:{counts['x']}  **.**:{counts['.']}", "",
      "### Tier-1 (income statement: 보험손익·투자손익·영업이익·세전·법인세·당기순 — from DART FS API)",
      f"- closes 22=20+21 (Tier-1 healthy): **{_stmt - counts['x']}/{_stmt}** cells.  "
      f"Only **{counts['x']}** fail (x) — those fell back to the legacy HTML parser (no API datum).",
      "- i/~ are NOT Tier-1 failures: those cells have a clean income statement.",
      "",
      "### Tier-2 (장기 CSM상각/위험조정/예실차 + 자동차/일반 decomposition — footnote, hand-parsed)",
      f"- reconciles (v+G): **{counts['v'] + counts['G']}**   present-but-off (~): **{counts['~']}**   "
      f"NOT extracted yet (i): **{counts['i']}**  ← the remaining work (DART FS API has no footnotes).",
      "",
      f"- structure-note (20≠1+17, 기타영업 present — informational, not an error): {len(struct)}", ""]
L += ["## Broken (x) — statement does not close (22 ≠ 20+21)", ""]
L += (["- " + b for b in broken] or ["- (none)"])
L += ["", "## Wobble (~) — Tier-2 does not reconcile (RC fails)", ""]
L += (["- " + w for w in wobble] or ["- (none)"])

(ROOT / "docs" / "pl_selfcheck_matrix.md").write_text("\n".join(L), encoding="utf-8")
print("wrote docs/pl_selfcheck_matrix.md")
print(f"G={counts['G']} v={counts['v']} i={counts['i']} ~={counts['~']} x={counts['x']} .={counts['.']}")
print(f"struct-note(20!=1+17): {len(struct)}")
print(f"broken({len(broken)}):", broken)
print(f"wobble({len(wobble)}):", wobble)
