"""Build CSM Movement Waterfall HISTORICAL (per-period) data.

Reads data/ifrs17/extracted_history/<canonical>__<period>_csm.json (output of
scripts/ifrs17_batch_historical.py) and emits
data/ifrs17/viz/csm_waterfall_history.json — a time-series of waterfalls
across 13 quarters (2023.1Q ~ 2026.1Q) for the IFRS17 universe.

Reuses pick_main_block / extract_stages from viz_build_csm_waterfall.py,
which already work on raw csm_extractor block lists (the historical
extracts use the same shape).

Output schema:
  {
    "unit": "million KRW",
    "periods": ["2023.1Q", ...],
    "stage_order": [...],
    "stage_labels_ko": {...},
    "companies": [
      {
        "company": "한화생명",
        "periods": {
          "2023.1Q": {"status": "ok", "stages": {...}, "completeness": 1.0},
          "2023.2Q": {"status": "no_csm_table_found"},
          ...
        }
      },
      ...
    ]
  }
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.stdout.reconfigure(encoding="utf-8")

# Reuse existing picker logic — no per-company hardcoded mapping
from scripts.viz_build_csm_waterfall import (  # noqa: E402
    deduplicate,
    detect_unit_scale,
    extract_stages,
    find_csm_leaf_cols,
    normalize_block_header,
    pick_main_block,
)

SRC_DIR = ROOT / "data" / "ifrs17" / "extracted_history"
OUT_DIR = ROOT / "data" / "ifrs17" / "viz"
OUT_DIR.mkdir(parents=True, exist_ok=True)
HIST_SUMMARY = SRC_DIR / "_historical_summary.json"

# Uses _measurement.json files (generated by ifrs17_promote_history_to_measurement.py).
# pick_main_block / extract_stages are tuned for measurement_extractor output.
PERIOD_RE = re.compile(r"^(?P<company>.+?)__(?P<period>\d{4}\.\d[QY])_measurement$")

STAGE_ORDER = [
    "opening", "new_business", "interest", "assumption", "amortization", "closing",
]
STAGE_LABELS_KO = {
    "opening": "기초",
    "new_business": "신계약",
    "interest": "이자부리",
    "assumption": "가정·경험 조정",
    "amortization": "상각",
    "closing": "기말",
}


def build_one_period(path: Path) -> dict:
    """Build per-period waterfall snapshot for one (company, period) file.

    Returns: {"status": "ok"|"partial"|"no_csm_table_found"|"empty_extract",
              "stages": {...}, "completeness": float, "caption": str, ...}
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"status": "json_error", "error": str(exc)}
    if not raw:
        return {"status": "empty_extract"}

    blocks = [normalize_block_header(b) for b in deduplicate(raw)]
    main = pick_main_block(blocks)
    if main is None:
        return {
            "status": "no_csm_block",
            "n_blocks_in_extract": len(blocks),
            "first_caption": blocks[0].get("caption") if blocks else None,
        }

    stages = extract_stages(main)
    if not stages:
        return {
            "status": "no_stage_match",
            "caption": main.get("caption"),
        }

    unit_div = detect_unit_scale(blocks)
    if unit_div == 1.0 and stages.get("opening"):
        opv = abs(stages["opening"]["value_mn_krw"])
        if opv > 1e10:
            unit_div = 1_000_000.0
        elif opv > 1e8:
            unit_div = 1_000.0
    if unit_div != 1.0:
        for s in stages.values():
            s["value_mn_krw"] = s["value_mn_krw"] / unit_div

    completeness = round(len(stages) / 6.0, 2)
    return {
        "status": "ok" if completeness >= 5 / 6 else "partial",
        "completeness": completeness,
        "caption": main.get("caption"),
        "unit_divisor_to_mn": unit_div,
        "stages": stages,
    }


def main() -> int:
    files = sorted(SRC_DIR.glob("*__*_measurement.json"))
    files = [f for f in files if not f.stem.startswith("_")]
    if not files:
        print(f"no historical extract files under {SRC_DIR}")
        return 1

    # Aggregate per company
    by_company: dict[str, dict[str, dict]] = {}
    periods_seen: set[str] = set()

    for f in files:
        m = PERIOD_RE.match(f.stem)
        if not m:
            print(f"skip (bad name): {f.name}")
            continue
        company = m.group("company")
        period = m.group("period")
        periods_seen.add(period)
        snap = build_one_period(f)
        by_company.setdefault(company, {})[period] = snap

    periods_sorted = sorted(periods_seen, key=lambda p: (int(p[:4]), int(p[5])))

    # Fill missing periods (no extract file at all — happens if no_filing in
    # historical batch). Also merge in no_filing status from _historical_summary.json.
    no_filing_map: dict[tuple[str, str], str] = {}
    if HIST_SUMMARY.exists():
        s = json.loads(HIST_SUMMARY.read_text(encoding="utf-8"))
        for r in s.get("results", []):
            canon = r.get("canonical") or ""
            period = r.get("period")
            st = r.get("status", "")
            if canon and period and st in ("no_filing", "download_error", "list_error"):
                no_filing_map[(canon, period)] = st
            elif canon and period and st.startswith("download_error"):
                no_filing_map[(canon, period)] = "download_error"

    companies_out = []
    for company in sorted(by_company.keys()):
        per_period = {}
        for p in periods_sorted:
            if p in by_company[company]:
                per_period[p] = by_company[company][p]
            elif (company, p) in no_filing_map:
                per_period[p] = {"status": no_filing_map[(company, p)]}
            else:
                per_period[p] = {"status": "no_extract"}
        companies_out.append({
            "company": company,
            "periods": per_period,
        })

    payload = {
        "unit": "million KRW",
        "periods": periods_sorted,
        "source": "DART periodic reports (scripts/ifrs17_batch_historical.py)",
        "stage_order": STAGE_ORDER,
        "stage_labels_ko": STAGE_LABELS_KO,
        "stage_labels_en": {
            "opening": "Opening net",
            "new_business": "New business",
            "interest": "Interest accretion",
            "assumption": "Assumption / experience",
            "amortization": "CSM amortization",
            "closing": "Closing net",
        },
        "companies": companies_out,
    }
    out = OUT_DIR / "csm_waterfall_history.json"
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {out}")

    # Summary
    print(f"companies: {len(companies_out)}")
    print(f"periods: {periods_sorted}")
    stat_counts: dict[str, int] = {}
    for c in companies_out:
        for p, sn in c["periods"].items():
            st = sn.get("status", "?")
            stat_counts[st] = stat_counts.get(st, 0) + 1
    print("status breakdown:")
    for st, n in sorted(stat_counts.items(), key=lambda x: -x[1]):
        print(f"  {st}: {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
